import { readFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import { describe, expect, it } from 'vitest';
import { getBrowserPage } from '../../browser/browser.js';
import { listFutureEvents } from './scrapper.js';

describe('#timePulse.listFutureEvents()', () => {
  it('should return list of all future events', async () => {
    const html = await readFile(
      resolve(__dirname, 'mocks/index.html'),
      'utf-8',
    );
    const { browser, page } = await getBrowserPage({
      'https://www.timepulse.fr/calendrier': {
        status: 200,
        contentType: 'text/html',
        body: html,
      },
    });

    const list = await listFutureEvents(1, { page });
    expect(list).toMatchInlineSnapshot(`
      [
        {
          "beginning": 1791504000000,
          "city": "Cholet",
          "departementNumber": 49,
          "ending": 1791504000000,
          "eventLink": "https://www.timepulse.fr/evenements/voir/3406/la-moine-express-2026-cholet",
          "eventType": "course_a_pied",
          "name": "La Moine Express 2026",
          "numberOfRaceVariants": "unknown",
          "place": "ASPTT Cholet, 65 avenue du lac",
          "registrationLink": "",
          "registrationStatus": "open",
        },
        {
          "beginning": 1791590400000,
          "city": "Pontchâteau",
          "departementNumber": 44,
          "ending": 1791590400000,
          "eventLink": "https://www.timepulse.fr/evenements/voir/3487/la-pontchatelaine-pontchateau",
          "eventType": "course_a_pied",
          "name": "La Pontchâtelaine",
          "numberOfRaceVariants": "unknown",
          "place": "Allée du Brivet, 44160 Pontchâteau",
          "registrationLink": "",
          "registrationStatus": "open",
        },
        {
          "beginning": 1791590400000,
          "city": "Avessac",
          "departementNumber": 44,
          "ending": 1791590400000,
          "eventLink": "https://www.timepulse.fr/evenements/voir/3310/trail-des-bezous-d-chataignes-avessac",
          "eventType": "course_a_pied",
          "name": "Trail des bezous d'Châtaignes",
          "numberOfRaceVariants": "unknown",
          "place": "Château du Pordor",
          "registrationLink": "",
          "registrationStatus": "open",
        },
        {
          "beginning": 1791590400000,
          "city": "Saint-Martin-Lestra",
          "departementNumber": 42,
          "ending": 1791590400000,
          "eventLink": "https://www.timepulse.fr/evenements/voir/3484/trail-des-bleuets-saint-martin-lestra",
          "eventType": "course_a_pied",
          "name": "Trail des bleuets",
          "numberOfRaceVariants": "unknown",
          "place": "Salle d'animation",
          "registrationLink": "",
          "registrationStatus": "open",
        },
        {
          "beginning": 1791676800000,
          "city": "Barbechat",
          "departementNumber": 44,
          "ending": 1791676800000,
          "eventLink": "https://www.timepulse.fr/evenements/voir/3499/barbecha-trail-2026-barbechat",
          "eventType": "course_a_pied",
          "name": "Barbecha’Trail 2026",
          "numberOfRaceVariants": "unknown",
          "place": "Salle du Bois Guillet",
          "registrationLink": "",
          "registrationStatus": "open",
        },
        {
          "beginning": 1791676800000,
          "city": "Saint-Hilaire-de-Clisson",
          "departementNumber": 44,
          "ending": 1791676800000,
          "eventLink": "https://www.timepulse.fr/evenements/voir/3359/les-foulees-hilairoises-saint-hilaire-de-clisson",
          "eventType": "course_a_pied",
          "name": "Les Foulées Hilairoises",
          "numberOfRaceVariants": "unknown",
          "place": "Stade de foot",
          "registrationLink": "",
          "registrationStatus": "open",
        },
        {
          "beginning": 1791676800000,
          "city": "Mayenne",
          "departementNumber": 53,
          "ending": 1791676800000,
          "eventLink": "https://www.timepulse.fr/evenements/voir/3291/ultra-trail-la-mayenne-mayenne",
          "eventType": "course_a_pied",
          "name": "Ultra Trail La Mayenne",
          "numberOfRaceVariants": "unknown",
          "place": "Le Halage Mayenne",
          "registrationLink": "",
          "registrationStatus": "open",
        },
        {
          "beginning": 1792195200000,
          "city": "Le Cellier",
          "departementNumber": 44,
          "ending": 1792195200000,
          "eventLink": "https://www.timepulse.fr/evenements/voir/3350/les-foulees-siffait-le-cellier",
          "eventType": "course_a_pied",
          "name": "Les Foulées Siffait",
          "numberOfRaceVariants": "unknown",
          "place": "Complexe sportif - rue de Langförden",
          "registrationLink": "",
          "registrationStatus": "open",
        },
        {
          "beginning": 1792281600000,
          "city": "Orléans",
          "departementNumber": 45,
          "ending": 1792281600000,
          "eventLink": "https://www.timepulse.fr/calendrier/voir/3324/courses-de-l-indien-edition-2026-50e-edition-orleans",
          "eventType": "course_a_pied",
          "name": "Courses de l'Indien - Edition 2026 (50e édition)",
          "numberOfRaceVariants": "unknown",
          "place": "Place Albert Camus",
          "registrationLink": "",
          "registrationStatus": "unknown",
        },
        {
          "beginning": 1792281600000,
          "city": "Saint-Nazaire",
          "departementNumber": 44,
          "ending": 1792281600000,
          "eventLink": "https://www.timepulse.fr/evenements/voir/3457/foulees-nazairiennes-2026-saint-nazaire",
          "eventType": "course_a_pied",
          "name": "Foulées Nazairiennes 2026",
          "numberOfRaceVariants": "unknown",
          "place": "Gymnase CARNOT rue du Traict",
          "registrationLink": "",
          "registrationStatus": "open",
        },
        {
          "beginning": 1792281600000,
          "city": "La Chapelle-sur-Erdre",
          "departementNumber": 44,
          "ending": 1792281600000,
          "eventLink": "https://www.timepulse.fr/evenements/voir/3418/ouaga-sur-erdre-2026-la-chapelle-sur-erdre",
          "eventType": "course_a_pied",
          "name": "OUAGA SUR ERDRE 2026",
          "numberOfRaceVariants": "unknown",
          "place": "Complexe sportif du Buisson de la GROLLE",
          "registrationLink": "",
          "registrationStatus": "open",
        },
        {
          "beginning": 1792281600000,
          "city": "La Remaudière",
          "departementNumber": 44,
          "ending": 1792281600000,
          "eventLink": "https://www.timepulse.fr/evenements/voir/3311/rrx-rem-run-experience-la-remaudiere-44-la-remaudiere",
          "eventType": "course_a_pied",
          "name": "RRX Rem Run Expérience - La Remaudière (44)",
          "numberOfRaceVariants": "unknown",
          "place": "MAIRIE - LA REMAUDIERE",
          "registrationLink": "",
          "registrationStatus": "open",
        },
        {
          "beginning": 1792281600000,
          "city": "Nantes",
          "departementNumber": 44,
          "ending": 1792281600000,
          "eventLink": "https://www.timepulse.fr/evenements/voir/3477/triathlon-de-nantes-nantes",
          "eventType": "triathlon",
          "name": "Triathlon de Nantes",
          "numberOfRaceVariants": "unknown",
          "place": "Piscine Léo Lagrange, Allée de l'Île Gloriette",
          "registrationLink": "",
          "registrationStatus": "open",
        },
        {
          "beginning": 1792886400000,
          "city": "Cholet",
          "departementNumber": 49,
          "ending": 1792886400000,
          "eventLink": "https://www.timepulse.fr/evenements/voir/3411/les-foulees-choletaises-cholet",
          "eventType": "course_a_pied",
          "name": "Les Foulées Choletaises",
          "numberOfRaceVariants": "unknown",
          "place": "Salle Omnisports",
          "registrationLink": "",
          "registrationStatus": "open",
        },
        {
          "beginning": 1792886400000,
          "city": "Nantes",
          "departementNumber": 44,
          "ending": 1792886400000,
          "eventLink": "https://www.timepulse.fr/evenements/voir/3417/trail-urbain-nantais-100eme-tour-de-chantenay-nantes",
          "eventType": "course_a_pied",
          "name": "Trail Urbain Nantais - 100ème Tour de Chantenay",
          "numberOfRaceVariants": "unknown",
          "place": "Boulevard de la Liberté Nantes Chantenay",
          "registrationLink": "",
          "registrationStatus": "open",
        },
        {
          "beginning": 1793404800000,
          "city": "Saint-Géréon",
          "departementNumber": 44,
          "ending": 1793404800000,
          "eventLink": "https://www.timepulse.fr/evenements/voir/3452/la-555-by-go-trail-3-saint-gereon",
          "eventType": "course_a_pied",
          "name": "La 555 by Go'Trail (#3)",
          "numberOfRaceVariants": "unknown",
          "place": "Ecole du Gotha",
          "registrationLink": "",
          "registrationStatus": "open",
        },
        {
          "beginning": 1793404800000,
          "city": "Bouaye",
          "departementNumber": 44,
          "ending": 1793404800000,
          "eventLink": "https://www.timepulse.fr/evenements/voir/3486/trail-nocturne-bosceen-bouaye",
          "eventType": "course_a_pied",
          "name": "TRAIL NOCTURNE BOSCEEN",
          "numberOfRaceVariants": "unknown",
          "place": "Ensemble sportif René Gautier",
          "registrationLink": "",
          "registrationStatus": "open",
        },
        {
          "beginning": 1794009600000,
          "city": "Bourgoin-Jallieu",
          "departementNumber": 38,
          "ending": 1794009600000,
          "eventLink": "https://www.timepulse.fr/calendrier/voir/3341/berjatrail-bourgoin-jallieu",
          "eventType": "course_a_pied",
          "name": "BERJATRAIL",
          "numberOfRaceVariants": "unknown",
          "place": "91 avenue professeur tixier",
          "registrationLink": "",
          "registrationStatus": "unknown",
        },
        {
          "beginning": 1794009600000,
          "city": "La Varenne",
          "departementNumber": 49,
          "ending": 1794009600000,
          "eventLink": "https://www.timepulse.fr/evenements/voir/3297/diva-trail-nocturne-la-varenne",
          "eventType": "course_a_pied",
          "name": "DIVA'TRAIL Nocturne",
          "numberOfRaceVariants": "unknown",
          "place": "ORÉE-D'ANJOU, Salle des Hautes Cartelles",
          "registrationLink": "",
          "registrationStatus": "open",
        },
        {
          "beginning": 1794355200000,
          "city": "Saint-Baudelle",
          "departementNumber": 53,
          "ending": 1794355200000,
          "eventLink": "https://www.timepulse.fr/evenements/voir/3503/foulees-baudelloises-saint-baudelle",
          "eventType": "course_a_pied",
          "name": "Foulées Baudelloises",
          "numberOfRaceVariants": "unknown",
          "place": "Salle des sports",
          "registrationLink": "",
          "registrationStatus": "open",
        },
        {
          "beginning": 1794700800000,
          "city": "Saint-Étienne-du-Rouvray",
          "departementNumber": 76,
          "ending": 1794700800000,
          "eventLink": "https://www.timepulse.fr/evenements/voir/3507/trail-du-rouvray-2026-saint-tienne-du-rouvray",
          "eventType": "course_a_pied",
          "name": "Trail du Rouvray 2026",
          "numberOfRaceVariants": "unknown",
          "place": "Gymnase de l'INSA 160 avenue Galilée",
          "registrationLink": "",
          "registrationStatus": "open",
        },
        {
          "beginning": 1795219200000,
          "city": "Saint-Michel-Chef-Chef",
          "departementNumber": 44,
          "ending": 1795219200000,
          "eventLink": "https://www.timepulse.fr/evenements/voir/3469/trail-de-la-cote-de-jade-noz-trail-15-km-defis-court-et-long-saint-michel-chef-chef",
          "eventType": "course_a_pied",
          "name": "Trail de la Cote de Jade: Noz Trail 15 km / Défis court et long",
          "numberOfRaceVariants": "unknown",
          "place": "Salle de la Viauderie",
          "registrationLink": "",
          "registrationStatus": "open",
        },
        {
          "beginning": 1795305600000,
          "city": "Saint-Michel-Chef-Chef",
          "departementNumber": 44,
          "ending": 1795305600000,
          "eventLink": "https://www.timepulse.fr/evenements/voir/3468/trail-de-la-cote-de-jade-11-km-26-km-trail-sport-adapte-saint-michel-chef-chef",
          "eventType": "course_a_pied",
          "name": "Trail de la Cote de Jade (11 km /26 km /Trail sport adapté)",
          "numberOfRaceVariants": "unknown",
          "place": "Salle de La Viauderie",
          "registrationLink": "",
          "registrationStatus": "open",
        },
        {
          "beginning": 1795824000000,
          "city": "Les Touches",
          "departementNumber": 44,
          "ending": 1795824000000,
          "eventLink": "https://www.timepulse.fr/evenements/voir/3500/trail-nocturne-touchois-les-touches",
          "eventType": "course_a_pied",
          "name": "Trail Nocturne Touchois",
          "numberOfRaceVariants": "unknown",
          "place": "Salle Omnisport",
          "registrationLink": "",
          "registrationStatus": "open",
        },
      ]
    `);

    await browser.close();
  });
});
