import { readFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import { describe, expect, it } from 'vitest';
import { getBrowserPage } from '../../browser/browser.js';
import { listFutureEvents } from './scrapper.js';

describe('#timePulse.listFutureEvents()', () => {
  it('should return list of all future events', async () => {
    const html = await readFile(
      resolve(__dirname, 'mocks/index.html'),
      'utf-8',
    );
    const { browser, page } = await getBrowserPage({
      'https://www.timepulse.fr/calendrier': {
        status: 200,
        contentType: 'text/html',
        body: html,
      },
    });

    const list = await listFutureEvents(1, { page });
    expect(list).toMatchInlineSnapshot(`
      [
        {
          "beginning": 1786233600000,
          "city": "Saint-Michel-Chef-Chef",
          "departementNumber": 44,
          "ending": 1786233600000,
          "eventLink": "https://www.timepulse.fr/evenements/voir/3422/les-foulees-micheloises-2026-saint-michel-chef-chef",
          "eventType": "course_a_pied",
          "name": "Les Foulées Micheloises 2026",
          "numberOfRaceVariants": "unknown",
          "place": "Complexe sportif de la Viauderie",
          "registrationLink": "",
          "registrationStatus": "open",
        },
        {
          "beginning": 1786233600000,
          "city": "Paris 15 Vaugirard",
          "departementNumber": 75,
          "ending": 1786233600000,
          "eventLink": "https://www.timepulse.fr/calendrier/voir/3511/edf-aqua-challenge-paris-paris-15-vaugirard",
          "eventType": "natation",
          "name": "EDF AQUA CHALLENGE PARIS",
          "numberOfRaceVariants": "unknown",
          "place": "BRAS DE GRENELLE - PARIS 15 VAUGIRARD (75)",
          "registrationLink": "",
          "registrationStatus": "unknown",
        },
        {
          "beginning": 1786752000000,
          "city": "Saint-Brevin-les-Pins",
          "departementNumber": 44,
          "ending": 1786752000000,
          "eventLink": "https://www.timepulse.fr/evenements/voir/3407/les-foulees-des-dunes-saint-brevin-les-pins",
          "eventType": "course_a_pied",
          "name": "Les Foulées des Dunes",
          "numberOfRaceVariants": "unknown",
          "place": "Boulevard de l'Océan (A proximité de l'Office du Tourisme situé Place Rene Guy Cadou ) Saint Brevin L'Océan.",
          "registrationLink": "",
          "registrationStatus": "open",
        },
        {
          "beginning": 1786752000000,
          "city": "Annecy",
          "departementNumber": 74,
          "ending": 1786752000000,
          "eventLink": "https://www.timepulse.fr/calendrier/voir/3512/traversee-du-lac-a-annecy-74-annecy",
          "eventType": "natation",
          "name": "Traversée du lac à ANNECY (74)",
          "numberOfRaceVariants": "unknown",
          "place": "Annecy",
          "registrationLink": "",
          "registrationStatus": "unknown",
        },
        {
          "beginning": 1787356800000,
          "city": "La Pommeraye",
          "departementNumber": 49,
          "ending": 1787443200000,
          "eventLink": "https://www.timepulse.fr/evenements/voir/3318/trail-des-moulins-2026-la-pommeraye",
          "eventType": "course_a_pied",
          "name": "Trail des Moulins 2026",
          "numberOfRaceVariants": "unknown",
          "place": "Stade de la Pommeraye",
          "registrationLink": "",
          "registrationStatus": "open",
        },
        {
          "beginning": 1787443200000,
          "city": "La Pommeraye",
          "departementNumber": 49,
          "ending": 1787443200000,
          "eventLink": "https://www.timepulse.fr/evenements/voir/3320/marche-nordique-trail-des-moulins-2026-la-pommeraye",
          "eventType": "marche_nordique",
          "name": "Marche Nordique Trail des Moulins 2026",
          "numberOfRaceVariants": "unknown",
          "place": "Stade de la Pommeraye",
          "registrationLink": "",
          "registrationStatus": "open",
        },
        {
          "beginning": 1788048000000,
          "city": "Couffé",
          "departementNumber": 44,
          "ending": 1788048000000,
          "eventLink": "https://www.timepulse.fr/evenements/voir/3335/trail-du-pont-noyer-couffe",
          "eventType": "course_a_pied",
          "name": "Trail du Pont Noyer",
          "numberOfRaceVariants": "unknown",
          "place": "Le Haut Vieux Couffé",
          "registrationLink": "",
          "registrationStatus": "open",
        },
        {
          "beginning": 1788048000000,
          "city": "Toulon",
          "departementNumber": 83,
          "ending": 1788134400000,
          "eventLink": "https://www.timepulse.fr/evenements/voir/3420/toulon-swim-race-toulon",
          "eventType": "natation",
          "name": "TOULON SWIM RACE",
          "numberOfRaceVariants": "unknown",
          "place": "Anse des Pins, Mourillon, Toulon",
          "registrationLink": "",
          "registrationStatus": "open",
        },
        {
          "beginning": 1788480000000,
          "city": "Argentan",
          "departementNumber": 61,
          "ending": 1788480000000,
          "eventLink": "https://www.timepulse.fr/evenements/voir/3234/10km-d-argentan-2026-argentan",
          "eventType": "course_a_pied",
          "name": "10km d'Argentan 2026",
          "numberOfRaceVariants": "unknown",
          "place": "Champ de foire",
          "registrationLink": "",
          "registrationStatus": "open",
        },
        {
          "beginning": 1788566400000,
          "city": "Boussay",
          "departementNumber": 44,
          "ending": 1788566400000,
          "eventLink": "https://www.timepulse.fr/evenements/voir/3363/les-sentiers-de-la-sevre-2026-boussay",
          "eventType": "course_a_pied",
          "name": "Les Sentiers de la Sèvre 2026",
          "numberOfRaceVariants": "unknown",
          "place": "salle omnisports",
          "registrationLink": "",
          "registrationStatus": "open",
        },
        {
          "beginning": 1788566400000,
          "city": "Château-Thébaud",
          "departementNumber": 44,
          "ending": 1788566400000,
          "eventLink": "https://www.timepulse.fr/evenements/voir/3400/rando-gravel-raid-nature-caffino-chateau-thebaud",
          "eventType": "gravel",
          "name": "Rando Gravel - Raid nature Caffino",
          "numberOfRaceVariants": "unknown",
          "place": "Base de loisirs Pont Caffino",
          "registrationLink": "",
          "registrationStatus": "open",
        },
        {
          "beginning": 1788652800000,
          "city": "Château-Thébaud",
          "departementNumber": 44,
          "ending": 1788652800000,
          "eventLink": "https://www.timepulse.fr/evenements/voir/3399/raid-caffino-2026-chateau-thebaud",
          "eventType": "raid_multisports",
          "name": "Raid Caffino 2026",
          "numberOfRaceVariants": "unknown",
          "place": "Base de loisirs Pont Caffino",
          "registrationLink": "",
          "registrationStatus": "open",
        },
        {
          "beginning": 1789171200000,
          "city": "Saint-Malo-de-Guersac",
          "departementNumber": 44,
          "ending": 1789171200000,
          "eventLink": "https://www.timepulse.fr/evenements/voir/3288/trail-tour-de-briere-annule-saint-malo-de-guersac",
          "eventType": "course_a_pied",
          "name": "Trail Tour de Brière - Annulé",
          "numberOfRaceVariants": "unknown",
          "place": "Site de Rozé - Saint-Malo-de-Guersac",
          "registrationLink": "",
          "registrationStatus": "open",
        },
        {
          "beginning": 1789171200000,
          "city": "Le Longeron",
          "departementNumber": 49,
          "ending": 1789171200000,
          "eventLink": "https://www.timepulse.fr/evenements/voir/3306/trail-du-bocage-longeronnais-le-longeron",
          "eventType": "course_a_pied",
          "name": "Trail du Bocage Longeronnais",
          "numberOfRaceVariants": "unknown",
          "place": "LE LONGERON (SEVREMOINE)",
          "registrationLink": "",
          "registrationStatus": "open",
        },
        {
          "beginning": 1789171200000,
          "city": "Montrelais",
          "departementNumber": 44,
          "ending": 1789171200000,
          "eventLink": "https://www.timepulse.fr/evenements/voir/3332/montrelais-en-couleurs-montrelais",
          "eventType": "course_a_pied",
          "name": "Montrelais en couleurs",
          "numberOfRaceVariants": "unknown",
          "place": "rue de l'espérance",
          "registrationLink": "",
          "registrationStatus": "open",
        },
        {
          "beginning": 1789171200000,
          "city": "Changé",
          "departementNumber": 53,
          "ending": 1789171200000,
          "eventLink": "https://www.timepulse.fr/evenements/voir/3419/la-petite-course-en-plus-change",
          "eventType": "course_a_pied",
          "name": "La petite course en plus",
          "numberOfRaceVariants": "unknown",
          "place": "Rue du Bac",
          "registrationLink": "",
          "registrationStatus": "open",
        },
        {
          "beginning": 1789257600000,
          "city": "Orvault",
          "departementNumber": 44,
          "ending": 1789257600000,
          "eventLink": "https://www.timepulse.fr/evenements/voir/3303/trail-cens-ationnel-orvault-orvault",
          "eventType": "course_a_pied",
          "name": "Trail Cens'Ationnel Orvault",
          "numberOfRaceVariants": "unknown",
          "place": "Complexe Sportif de la Frébaudiere 14 Rue du Raffuneau, 44700 Orvault",
          "registrationLink": "",
          "registrationStatus": "open",
        },
        {
          "beginning": 1789257600000,
          "city": "Juigné-sur-Loire",
          "departementNumber": 49,
          "ending": 1789257600000,
          "eventLink": "https://www.timepulse.fr/evenements/voir/3353/trail-loire-et-vignes-12eme-edition-juigne-sur-loire",
          "eventType": "course_a_pied",
          "name": "Trail Loire et Vignes - 12ème édition -",
          "numberOfRaceVariants": "unknown",
          "place": "chemin de la societe",
          "registrationLink": "",
          "registrationStatus": "open",
        },
        {
          "beginning": 1789689600000,
          "city": "La Pommeraye",
          "departementNumber": 49,
          "ending": 1789689600000,
          "eventLink": "https://www.timepulse.fr/evenements/voir/3392/marathon-relais-inter-entreprises-la-pommeraye",
          "eventType": "course_a_pied",
          "name": "Marathon Relais Inter-entreprises",
          "numberOfRaceVariants": "unknown",
          "place": "Stade de la Pommeraye",
          "registrationLink": "",
          "registrationStatus": "open",
        },
        {
          "beginning": 1789689600000,
          "city": "Clisson",
          "departementNumber": 44,
          "ending": 1789776000000,
          "eventLink": "https://www.timepulse.fr/evenements/voir/3396/trail-des-3-provinces-clisson",
          "eventType": "course_a_pied",
          "name": "Trail des 3 Provinces",
          "numberOfRaceVariants": "unknown",
          "place": "HELLCITY et HELLFEST - 44190 Clisson",
          "registrationLink": "",
          "registrationStatus": "open",
        },
        {
          "beginning": 1789862400000,
          "city": "Herbignac",
          "departementNumber": 44,
          "ending": 1789862400000,
          "eventLink": "https://www.timepulse.fr/evenements/voir/3314/le-defi-de-la-pierre-herbignac",
          "eventType": "course_a_pied",
          "name": "Le Défi de La Pierre",
          "numberOfRaceVariants": "unknown",
          "place": "carrière de La Clarté",
          "registrationLink": "",
          "registrationStatus": "open",
        },
        {
          "beginning": 1789862400000,
          "city": "Saint-Brevin-les-Pins",
          "departementNumber": 44,
          "ending": 1789862400000,
          "eventLink": "https://www.timepulse.fr/evenements/voir/3293/les-foulees-du-pont-saint-brevin-les-pins",
          "eventType": "course_a_pied",
          "name": "Les Foulées du Pont",
          "numberOfRaceVariants": "unknown",
          "place": "Place Bougainville",
          "registrationLink": "",
          "registrationStatus": "open",
        },
        {
          "beginning": 1789862400000,
          "city": "Saint-Herblain",
          "departementNumber": 44,
          "ending": 1789862400000,
          "eventLink": "https://www.timepulse.fr/evenements/voir/3348/les-foulees-vertes-de-la-gournerie-saint-herblain",
          "eventType": "course_a_pied",
          "name": "Les Foulées vertes de La Gournerie",
          "numberOfRaceVariants": "unknown",
          "place": "Parc de La Gournerie",
          "registrationLink": "",
          "registrationStatus": "open",
        },
        {
          "beginning": 1789862400000,
          "city": "Les Herbiers",
          "departementNumber": 85,
          "ending": 1789862400000,
          "eventLink": "https://www.timepulse.fr/evenements/voir/3404/10-km-des-herbiers-2026-les-herbiers",
          "eventType": "course_a_pied",
          "name": "10 Km des Herbiers 2026",
          "numberOfRaceVariants": "unknown",
          "place": "Centre d'Incendie et de Secours Des Herbiers",
          "registrationLink": "",
          "registrationStatus": "open",
        },
        {
          "beginning": 1789862400000,
          "city": "Cossé-le-Vivien",
          "departementNumber": 53,
          "ending": 1789862400000,
          "eventLink": "https://www.timepulse.fr/evenements/voir/3425/cosse-le-vise-bien-cosse-le-vivien",
          "eventType": "course_a_pied",
          "name": "Cossé le Vise Bien",
          "numberOfRaceVariants": "unknown",
          "place": "impasse du parc",
          "registrationLink": "",
          "registrationStatus": "open",
        },
        {
          "beginning": 1790380800000,
          "city": "Indre",
          "departementNumber": 44,
          "ending": 1790380800000,
          "eventLink": "https://www.timepulse.fr/evenements/voir/3339/6eme-edition-des-foulees-viikings-indre",
          "eventType": "course_a_pied",
          "name": "6ème édition des FOULEES VIIKINGS",
          "numberOfRaceVariants": "unknown",
          "place": "Village Viikings - Salle des 3 iles - Rue des Chaintres",
          "registrationLink": "",
          "registrationStatus": "open",
        },
        {
          "beginning": 1790380800000,
          "city": "Saint-Lyphard",
          "departementNumber": 44,
          "ending": 1790380800000,
          "eventLink": "https://www.timepulse.fr/evenements/voir/3358/foulees-lyphardaises-saint-lyphard",
          "eventType": "course_a_pied",
          "name": "Foulées Lyphardaises",
          "numberOfRaceVariants": "unknown",
          "place": "Rue de Bretagne",
          "registrationLink": "",
          "registrationStatus": "open",
        },
        {
          "beginning": 1790380800000,
          "city": "Saint-Léger-les-Vignes",
          "departementNumber": 44,
          "ending": 1790380800000,
          "eventLink": "https://www.timepulse.fr/calendrier/voir/3509/trail-des-vendanges-saint-leger-les-vignes",
          "eventType": "course_a_pied",
          "name": "Trail des vendanges",
          "numberOfRaceVariants": "unknown",
          "place": "salle omnisports- site de la rive",
          "registrationLink": "",
          "registrationStatus": "unknown",
        },
        {
          "beginning": 1790467200000,
          "city": "Saint-Cloud",
          "departementNumber": 92,
          "ending": 1790467200000,
          "eventLink": "https://www.timepulse.fr/evenements/voir/3269/course-enfants-sans-cancer-2026-saint-cloud",
          "eventType": "course_a_pied",
          "name": "Course Enfants sans Cancer 2026",
          "numberOfRaceVariants": "unknown",
          "place": "Domaine national de Saint-Cloud",
          "registrationLink": "",
          "registrationStatus": "open",
        },
        {
          "beginning": 1790467200000,
          "city": "Varades",
          "departementNumber": 44,
          "ending": 1790467200000,
          "eventLink": "https://www.timepulse.fr/evenements/voir/3270/run-in-varades-varades",
          "eventType": "course_a_pied",
          "name": "Run'In VARADES",
          "numberOfRaceVariants": "unknown",
          "place": "RUE DE L'ARCHE",
          "registrationLink": "",
          "registrationStatus": "open",
        },
        {
          "beginning": 1790467200000,
          "city": "Nantes",
          "departementNumber": 44,
          "ending": 1790467200000,
          "eventLink": "https://www.timepulse.fr/evenements/voir/3361/la-dag-nantes",
          "eventType": "course_a_pied",
          "name": "La DAG",
          "numberOfRaceVariants": "unknown",
          "place": "Stade de La Beaujoire",
          "registrationLink": "",
          "registrationStatus": "open",
        },
        {
          "beginning": 1790467200000,
          "city": "La Haie-Fouassière",
          "departementNumber": 44,
          "ending": 1790467200000,
          "eventLink": "https://www.timepulse.fr/evenements/voir/3458/courses-et-marche-des-vendangeurs-la-haie-fouassiere",
          "eventType": "course_a_pied",
          "name": "Courses et Marche des Vendangeurs",
          "numberOfRaceVariants": "unknown",
          "place": "Château de Rochefort",
          "registrationLink": "",
          "registrationStatus": "open",
        },
        {
          "beginning": 1790467200000,
          "city": "Nantes",
          "departementNumber": 44,
          "ending": 1790467200000,
          "eventLink": "https://www.timepulse.fr/evenements/voir/3480/les-foulees-du-vieux-doulon-nantes",
          "eventType": "course_a_pied",
          "name": "Les foulées du vieux-doulon",
          "numberOfRaceVariants": "unknown",
          "place": "Parc du grand blottereau",
          "registrationLink": "",
          "registrationStatus": "open",
        },
      ]
    `);

    await browser.close();
  });
});
