import { readFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import { describe, expect, it } from 'vitest';
import { getBrowserPage } from '../../browser/browser.js';
import { listFutureEvents } from './scrapper.js';

describe('#timePulse.listFutureEvents()', () => {
  it('should return list of all future events', async () => {
    const html = await readFile(
      resolve(__dirname, 'mocks/index.html'),
      'utf-8',
    );
    const { browser, page } = await getBrowserPage({
      'https://www.timepulse.fr/calendrier': {
        status: 200,
        contentType: 'text/html',
        body: html,
      },
    });

    const list = await listFutureEvents(1, { page });
    expect(list).toMatchInlineSnapshot(`
      [
        {
          "beginning": 1786233600000,
          "city": "Saint-Michel-Chef-Chef",
          "departementNumber": 44,
          "ending": 1786233600000,
          "eventLink": "https://www.timepulse.fr/evenements/voir/3422/les-foulees-micheloises-2026-saint-michel-chef-chef",
          "eventType": "course_a_pied",
          "name": "Les Foulées Micheloises 2026",
          "numberOfRaceVariants": "unknown",
          "place": "Complexe sportif de la Viauderie",
          "registrationLink": "",
          "registrationStatus": "open",
        },
        {
          "beginning": 1786233600000,
          "city": "Paris 15 Vaugirard",
          "departementNumber": 75,
          "ending": 1786233600000,
          "eventLink": "https://www.timepulse.fr/calendrier/voir/3511/edf-aqua-challenge-paris-paris-15-vaugirard",
          "eventType": "natation",
          "name": "EDF AQUA CHALLENGE PARIS",
          "numberOfRaceVariants": "unknown",
          "place": "BRAS DE GRENELLE - PARIS 15 VAUGIRARD (75)",
          "registrationLink": "",
          "registrationStatus": "unknown",
        },
        {
          "beginning": 1786752000000,
          "city": "Saint-Brevin-les-Pins",
          "departementNumber": 44,
          "ending": 1786752000000,
          "eventLink": "https://www.timepulse.fr/evenements/voir/3407/les-foulees-des-dunes-saint-brevin-les-pins",
          "eventType": "course_a_pied",
          "name": "Les Foulées des Dunes",
          "numberOfRaceVariants": "unknown",
          "place": "Boulevard de l'Océan (A proximité de l'Office du Tourisme situé Place Rene Guy Cadou ) Saint Brevin L'Océan.",
          "registrationLink": "",
          "registrationStatus": "open",
        },
        {
          "beginning": 1786752000000,
          "city": "Annecy",
          "departementNumber": 74,
          "ending": 1786752000000,
          "eventLink": "https://www.timepulse.fr/calendrier/voir/3512/traversee-du-lac-a-annecy-74-annecy",
          "eventType": "natation",
          "name": "Traversée du lac à ANNECY (74)",
          "numberOfRaceVariants": "unknown",
          "place": "Annecy",
          "registrationLink": "",
          "registrationStatus": "unknown",
        },
        {
          "beginning": 1787356800000,
          "city": "La Pommeraye",
          "departementNumber": 49,
          "ending": 1787443200000,
          "eventLink": "https://www.timepulse.fr/evenements/voir/3318/trail-des-moulins-2026-la-pommeraye",
          "eventType": "course_a_pied",
          "name": "Trail des Moulins 2026",
          "numberOfRaceVariants": "unknown",
          "place": "Stade de la Pommeraye",
          "registrationLink": "",
          "registrationStatus": "open",
        },
        {
          "beginning": 1787443200000,
          "city": "La Pommeraye",
          "departementNumber": 49,
          "ending": 1787443200000,
          "eventLink": "https://www.timepulse.fr/evenements/voir/3320/marche-nordique-trail-des-moulins-2026-la-pommeraye",
          "eventType": "marche_nordique",
          "name": "Marche Nordique Trail des Moulins 2026",
          "numberOfRaceVariants": "unknown",
          "place": "Stade de la Pommeraye",
          "registrationLink": "",
          "registrationStatus": "open",
        },
        {
          "beginning": 1788048000000,
          "city": "Couffé",
          "departementNumber": 44,
          "ending": 1788048000000,
          "eventLink": "https://www.timepulse.fr/evenements/voir/3335/trail-du-pont-noyer-couffe",
          "eventType": "course_a_pied",
          "name": "Trail du Pont Noyer",
          "numberOfRaceVariants": "unknown",
          "place": "Le Haut Vieux Couffé",
          "registrationLink": "",
          "registrationStatus": "open",
        },
        {
          "beginning": 1788048000000,
          "city": "Toulon",
          "departementNumber": 83,
          "ending": 1788134400000,
          "eventLink": "https://www.timepulse.fr/evenements/voir/3420/toulon-swim-race-toulon",
          "eventType": "natation",
          "name": "TOULON SWIM RACE",
          "numberOfRaceVariants": "unknown",
          "place": "Anse des Pins, Mourillon, Toulon",
          "registrationLink": "",
          "registrationStatus": "open",
        },
        {
          "beginning": 1788480000000,
          "city": "Argentan",
          "departementNumber": 61,
          "ending": 1788480000000,
          "eventLink": "https://www.timepulse.fr/evenements/voir/3234/10km-d-argentan-2026-argentan",
          "eventType": "course_a_pied",
          "name": "10km d'Argentan 2026",
          "numberOfRaceVariants": "unknown",
          "place": "Champ de foire",
          "registrationLink": "",
          "registrationStatus": "open",
        },
        {
          "beginning": 1788566400000,
          "city": "Boussay",
          "departementNumber": 44,
          "ending": 1788566400000,
          "eventLink": "https://www.timepulse.fr/evenements/voir/3363/les-sentiers-de-la-sevre-2026-boussay",
          "eventType": "course_a_pied",
          "name": "Les Sentiers de la Sèvre 2026",
          "numberOfRaceVariants": "unknown",
          "place": "salle omnisports",
          "registrationLink": "",
          "registrationStatus": "open",
        },
        {
          "beginning": 1788566400000,
          "city": "Château-Thébaud",
          "departementNumber": 44,
          "ending": 1788566400000,
          "eventLink": "https://www.timepulse.fr/evenements/voir/3400/rando-gravel-raid-nature-caffino-chateau-thebaud",
          "eventType": "gravel",
          "name": "Rando Gravel - Raid nature Caffino",
          "numberOfRaceVariants": "unknown",
          "place": "Base de loisirs Pont Caffino",
          "registrationLink": "",
          "registrationStatus": "open",
        },
        {
          "beginning": 1788652800000,
          "city": "Château-Thébaud",
          "departementNumber": 44,
          "ending": 1788652800000,
          "eventLink": "https://www.timepulse.fr/evenements/voir/3399/raid-caffino-2026-chateau-thebaud",
          "eventType": "raid_multisports",
          "name": "Raid Caffino 2026",
          "numberOfRaceVariants": "unknown",
          "place": "Base de loisirs Pont Caffino",
          "registrationLink": "",
          "registrationStatus": "open",
        },
        {
          "beginning": 1789171200000,
          "city": "Saint-Malo-de-Guersac",
          "departementNumber": 44,
          "ending": 1789171200000,
          "eventLink": "https://www.timepulse.fr/evenements/voir/3288/trail-tour-de-briere-annule-saint-malo-de-guersac",
          "eventType": "course_a_pied",
          "name": "Trail Tour de Brière - Annulé",
          "numberOfRaceVariants": "unknown",
          "place": "Site de Rozé - Saint-Malo-de-Guersac",
          "registrationLink": "",
          "registrationStatus": "open",
        },
        {
          "beginning": 1789171200000,
          "city": "Le Longeron",
          "departementNumber": 49,
          "ending": 1789171200000,
          "eventLink": "https://www.timepulse.fr/evenements/voir/3306/trail-du-bocage-longeronnais-le-longeron",
          "eventType": "course_a_pied",
          "name": "Trail du Bocage Longeronnais",
          "numberOfRaceVariants": "unknown",
          "place": "LE LONGERON (SEVREMOINE)",
          "registrationLink": "",
          "registrationStatus": "open",
        },
        {
          "beginning": 1789171200000,
          "city": "Montrelais",
          "departementNumber": 44,
          "ending": 1789171200000,
          "eventLink": "https://www.timepulse.fr/evenements/voir/3332/montrelais-en-couleurs-montrelais",
          "eventType": "course_a_pied",
          "name": "Montrelais en couleurs",
          "numberOfRaceVariants": "unknown",
          "place": "rue de l'espérance",
          "registrationLink": "",
          "registrationStatus": "open",
        },
        {
          "beginning": 1789171200000,
          "city": "Changé",
          "departementNumber": 53,
          "ending": 1789171200000,
          "eventLink": "https://www.timepulse.fr/evenements/voir/3419/la-petite-course-en-plus-change",
          "eventType": "course_a_pied",
          "name": "La petite course en plus",
          "numberOfRaceVariants": "unknown",
          "place": "Rue du Bac",
          "registrationLink": "",
          "registrationStatus": "open",
        },
        {
          "beginning": 1789257600000,
          "city": "Orvault",
          "departementNumber": 44,
          "ending": 1789257600000,
          "eventLink": "https://www.timepulse.fr/evenements/voir/3303/trail-cens-ationnel-orvault-orvault",
          "eventType": "course_a_pied",
          "name": "Trail Cens'Ationnel Orvault",
          "numberOfRaceVariants": "unknown",
          "place": "Complexe Sportif de la Frébaudiere 14 Rue du Raffuneau, 44700 Orvault",
          "registrationLink": "",
          "registrationStatus": "open",
        },
        {
          "beginning": 1789257600000,
          "city": "Juigné-sur-Loire",
          "departementNumber": 49,
          "ending": 1789257600000,
          "eventLink": "https://www.timepulse.fr/evenements/voir/3353/trail-loire-et-vignes-12eme-edition-juigne-sur-loire",
          "eventType": "course_a_pied",
          "name": "Trail Loire et Vignes - 12ème édition -",
          "numberOfRaceVariants": "unknown",
          "place": "chemin de la societe",
          "registrationLink": "",
          "registrationStatus": "open",
        },
        {
          "beginning": 1789689600000,
          "city": "La Pommeraye",
          "departementNumber": 49,
          "ending": 1789689600000,
          "eventLink": "https://www.timepulse.fr/evenements/voir/3392/marathon-relais-inter-entreprises-la-pommeraye",
          "eventType": "course_a_pied",
          "name": "Marathon Relais Inter-entreprises",
          "numberOfRaceVariants": "unknown",
          "place": "Stade de la Pommeraye",
          "registrationLink": "",
          "registrationStatus": "open",
        },
        {
          "beginning": 1789689600000,
          "city": "Clisson",
          "departementNumber": 44,
          "ending": 1789776000000,
          "eventLink": "https://www.timepulse.fr/evenements/voir/3396/trail-des-3-provinces-clisson",
          "eventType": "course_a_pied",
          "name": "Trail des 3 Provinces",
          "numberOfRaceVariants": "unknown",
          "place": "HELLCITY et HELLFEST - 44190 Clisson",
          "registrationLink": "",
          "registrationStatus": "open",
        },
        {
          "beginning": 1789862400000,
          "city": "Herbignac",
          "departementNumber": 44,
          "ending": 1789862400000,
          "eventLink": "https://www.timepulse.fr/evenements/voir/3314/le-defi-de-la-pierre-herbignac",
          "eventType": "course_a_pied",
          "name": "Le Défi de La Pierre",
          "numberOfRaceVariants": "unknown",
          "place": "carrière de La Clarté",
          "registrationLink": "",
          "registrationStatus": "open",
        },
        {
          "beginning": 1789862400000,
          "city": "Saint-Brevin-les-Pins",
          "departementNumber": 44,
          "ending": 1789862400000,
          "eventLink": "https://www.timepulse.fr/evenements/voir/3293/les-foulees-du-pont-saint-brevin-les-pins",
          "eventType": "course_a_pied",
          "name": "Les Foulées du Pont",
          "numberOfRaceVariants": "unknown",
          "place": "Place Bougainville",
          "registrationLink": "",
          "registrationStatus": "open",
        },
        {
          "beginning": 1789862400000,
          "city": "Saint-Herblain",
          "departementNumber": 44,
          "ending": 1789862400000,
          "eventLink": "https://www.timepulse.fr/evenements/voir/3348/les-foulees-vertes-de-la-gournerie-saint-herblain",
          "eventType": "course_a_pied",
          "name": "Les Foulées vertes de La Gournerie",
          "numberOfRaceVariants": "unknown",
          "place": "Parc de La Gournerie",
          "registrationLink": "",
          "registrationStatus": "open",
        },
        {
          "beginning": 1789862400000,
          "city": "Les Herbiers",
          "departementNumber": 85,
          "ending": 1789862400000,
          "eventLink": "https://www.timepulse.fr/evenements/voir/3404/10-km-des-herbiers-2026-les-herbiers",
          "eventType": "course_a_pied",
          "name": "10 Km des Herbiers 2026",
          "numberOfRaceVariants": "unknown",
          "place": "Centre d'Incendie et de Secours Des Herbiers",
          "registrationLink": "",
          "registrationStatus": "open",
        },
        {
          "beginning": 1789862400000,
          "city": "Cossé-le-Vivien",
          "departementNumber": 53,
          "ending": 1789862400000,
          "eventLink": "https://www.timepulse.fr/evenements/voir/3425/cosse-le-vise-bien-cosse-le-vivien",
          "eventType": "course_a_pied",
          "name": "Cossé le Vise Bien",
          "numberOfRaceVariants": "unknown",
          "place": "impasse du parc",
          "registrationLink": "",
          "registrationStatus": "open",
        },
        {
          "beginning": 1790380800000,
          "city": "Indre",
          "departementNumber": 44,
          "ending": 1790380800000,
          "eventLink": "https://www.timepulse.fr/evenements/voir/3339/6eme-edition-des-foulees-viikings-indre",
          "eventType": "course_a_pied",
          "name": "6ème édition des FOULEES VIIKINGS",
          "numberOfRaceVariants": "unknown",
          "place": "Village Viikings - Salle des 3 iles - Rue des Chaintres",
          "registrationLink": "",
          "registrationStatus": "open",
        },
        {
          "beginning": 1790380800000,
          "city": "Saint-Lyphard",
          "departementNumber": 44,
          "ending": 1790380800000,
          "eventLink": "https://www.timepulse.fr/evenements/voir/3358/foulees-lyphardaises-saint-lyphard",
          "eventType": "course_a_pied",
          "name": "Foulées Lyphardaises",
          "numberOfRaceVariants": "unknown",
          "place": "Rue de Bretagne",
          "registrationLink": "",
          "registrationStatus": "open",
        },
        {
          "beginning": 1790380800000,
          "city": "Saint-Léger-les-Vignes",
          "departementNumber": 44,
          "ending": 1790380800000,
          "eventLink": "https://www.timepulse.fr/calendrier/voir/3509/trail-des-vendanges-saint-leger-les-vignes",
          "eventType": "course_a_pied",
          "name": "Trail des vendanges",
          "numberOfRaceVariants": "unknown",
          "place": "salle omnisports- site de la rive",
          "registrationLink": "",
          "registrationStatus": "unknown",
        },
        {
          "beginning": 1790467200000,
          "city": "Saint-Cloud",
          "departementNumber": 92,
          "ending": 1790467200000,
          "eventLink": "https://www.timepulse.fr/evenements/voir/3269/course-enfants-sans-cancer-2026-saint-cloud",
          "eventType": "course_a_pied",
          "name": "Course Enfants sans Cancer 2026",
          "numberOfRaceVariants": "unknown",
          "place": "Domaine national de Saint-Cloud",
          "registrationLink": "",
          "registrationStatus": "open",
        },
        {
          "beginning": 1790467200000,
          "city": "Varades",
          "departementNumber": 44,
          "ending": 1790467200000,
          "eventLink": "https://www.timepulse.fr/evenements/voir/3270/run-in-varades-varades",
          "eventType": "course_a_pied",
          "name": "Run'In VARADES",
          "numberOfRaceVariants": "unknown",
          "place": "RUE DE L'ARCHE",
          "registrationLink": "",
          "registrationStatus": "open",
        },
        {
          "beginning": 1790467200000,
          "city": "Nantes",
          "departementNumber": 44,
          "ending": 1790467200000,
          "eventLink": "https://www.timepulse.fr/evenements/voir/3361/la-dag-nantes",
          "eventType": "course_a_pied",
          "name": "La DAG",
          "numberOfRaceVariants": "unknown",
          "place": "Stade de La Beaujoire",
          "registrationLink": "",
          "registrationStatus": "open",
        },
        {
          "beginning": 1790467200000,
          "city": "La Haie-Fouassière",
          "departementNumber": 44,
          "ending": 1790467200000,
          "eventLink": "https://www.timepulse.fr/evenements/voir/3458/courses-et-marche-des-vendangeurs-la-haie-fouassiere",
          "eventType": "course_a_pied",
          "name": "Courses et Marche des Vendangeurs",
          "numberOfRaceVariants": "unknown",
          "place": "Château de Rochefort",
          "registrationLink": "",
          "registrationStatus": "open",
        },
        {
          "beginning": 1790467200000,
          "city": "Nantes",
          "departementNumber": 44,
          "ending": 1790467200000,
          "eventLink": "https://www.timepulse.fr/evenements/voir/3480/les-foulees-du-vieux-doulon-nantes",
          "eventType": "course_a_pied",
          "name": "Les foulées du vieux-doulon",
          "numberOfRaceVariants": "unknown",
          "place": "Parc du grand blottereau",
          "registrationLink": "",
          "registrationStatus": "open",
        },
        {
          "beginning": 1790985600000,
          "city": "Brissac-Quincé",
          "departementNumber": 49,
          "ending": 1790985600000,
          "eventLink": "https://www.timepulse.fr/evenements/voir/3490/anjou-r-amp-nuit-brissac-quince",
          "eventType": "course_a_pied",
          "name": "ANJOU’R & NUIT",
          "numberOfRaceVariants": "unknown",
          "place": "Ecuries Château de Brissac",
          "registrationLink": "",
          "registrationStatus": "open",
        },
        {
          "beginning": 1791072000000,
          "city": "Mauves-sur-Loire",
          "departementNumber": 44,
          "ending": 1791072000000,
          "eventLink": "https://www.timepulse.fr/evenements/voir/3369/trail-de-mauves-en-vert-2026-mauves-sur-loire",
          "eventType": "course_a_pied",
          "name": "Trail de Mauves en Vert 2026",
          "numberOfRaceVariants": "unknown",
          "place": "Gare de Mauves sur Loire",
          "registrationLink": "",
          "registrationStatus": "open",
        },
        {
          "beginning": 1791072000000,
          "city": "Vertou",
          "departementNumber": 44,
          "ending": 1791072000000,
          "eventLink": "https://www.timepulse.fr/evenements/voir/3368/foulees-de-vertou-2026-vertou",
          "eventType": "course_a_pied",
          "name": "Foulées de Vertou 2026",
          "numberOfRaceVariants": "unknown",
          "place": "Parc du Loiry, Boulevard Guichet Serex, 44120 Vertou",
          "registrationLink": "",
          "registrationStatus": "open",
        },
        {
          "beginning": 1791072000000,
          "city": "Nantes",
          "departementNumber": 44,
          "ending": 1791072000000,
          "eventLink": "https://www.timepulse.fr/evenements/voir/3403/ekiden-de-nantes-by-decathlon-atlantis-nantes",
          "eventType": "course_a_pied",
          "name": "Ekiden de Nantes by Decathlon Atlantis",
          "numberOfRaceVariants": "unknown",
          "place": "Stadium Pierre Quinon",
          "registrationLink": "",
          "registrationStatus": "open",
        },
        {
          "beginning": 1791072000000,
          "city": "Argenton-les-Vallées",
          "departementNumber": 79,
          "ending": 1791072000000,
          "eventLink": "https://www.timepulse.fr/evenements/voir/3413/trail-de-l-argentonnay-2026-argenton-les-vallees",
          "eventType": "course_a_pied",
          "name": "Trail de l’Argentonnay 2026",
          "numberOfRaceVariants": "unknown",
          "place": "Rue de la Gendarmerie",
          "registrationLink": "",
          "registrationStatus": "open",
        },
        {
          "beginning": 1791072000000,
          "city": "Olivet",
          "departementNumber": 45,
          "ending": 1791072000000,
          "eventLink": "https://www.timepulse.fr/evenements/voir/3459/les-foulees-roses-olivet",
          "eventType": "course_a_pied",
          "name": "Les Foulées Roses",
          "numberOfRaceVariants": "unknown",
          "place": "54 rue des Chênes",
          "registrationLink": "",
          "registrationStatus": "open",
        },
        {
          "beginning": 1791072000000,
          "city": "Saint-Georges-sur-Loire",
          "departementNumber": 49,
          "ending": 1791072000000,
          "eventLink": "https://www.timepulse.fr/evenements/voir/3494/anjou-r-amp-nuit-saint-georges-sur-loire",
          "eventType": "course_a_pied",
          "name": "ANJOU’R & NUIT",
          "numberOfRaceVariants": "unknown",
          "place": "Jardins de L’Abbaye",
          "registrationLink": "",
          "registrationStatus": "open",
        },
        {
          "beginning": 1791072000000,
          "city": "Couëron",
          "departementNumber": 44,
          "ending": 1791072000000,
          "eventLink": "https://www.timepulse.fr/evenements/voir/3409/cou-ron-duathlon-2026-coueron",
          "eventType": "duathlon",
          "name": "COUËRON DUATHLON - 2026",
          "numberOfRaceVariants": "unknown",
          "place": "Kiosque à musique de Couëron",
          "registrationLink": "",
          "registrationStatus": "open",
        },
        {
          "beginning": 1791504000000,
          "city": "Cholet",
          "departementNumber": 49,
          "ending": 1791504000000,
          "eventLink": "https://www.timepulse.fr/evenements/voir/3406/la-moine-express-2026-cholet",
          "eventType": "course_a_pied",
          "name": "La Moine Express 2026",
          "numberOfRaceVariants": "unknown",
          "place": "ASPTT Cholet, 65 avenue du lac",
          "registrationLink": "",
          "registrationStatus": "open",
        },
        {
          "beginning": 1791590400000,
          "city": "Avessac",
          "departementNumber": 44,
          "ending": 1791590400000,
          "eventLink": "https://www.timepulse.fr/evenements/voir/3310/trail-des-bezous-d-chataignes-avessac",
          "eventType": "course_a_pied",
          "name": "Trail des bezous d'Châtaignes",
          "numberOfRaceVariants": "unknown",
          "place": "Château du Pordor",
          "registrationLink": "",
          "registrationStatus": "open",
        },
        {
          "beginning": 1791590400000,
          "city": "Saint-Martin-Lestra",
          "departementNumber": 42,
          "ending": 1791590400000,
          "eventLink": "https://www.timepulse.fr/evenements/voir/3484/trail-des-bleuets-saint-martin-lestra",
          "eventType": "course_a_pied",
          "name": "Trail des bleuets",
          "numberOfRaceVariants": "unknown",
          "place": "Salle d'animation",
          "registrationLink": "",
          "registrationStatus": "open",
        },
        {
          "beginning": 1791590400000,
          "city": "Pontchâteau",
          "departementNumber": 44,
          "ending": 1791590400000,
          "eventLink": "https://www.timepulse.fr/evenements/voir/3487/la-pontchatelaine-pontchateau",
          "eventType": "course_a_pied",
          "name": "La Pontchâtelaine",
          "numberOfRaceVariants": "unknown",
          "place": "Allée du Brivet, 44160 Pontchâteau",
          "registrationLink": "",
          "registrationStatus": "open",
        },
        {
          "beginning": 1791676800000,
          "city": "Mayenne",
          "departementNumber": 53,
          "ending": 1791676800000,
          "eventLink": "https://www.timepulse.fr/evenements/voir/3291/ultra-trail-la-mayenne-mayenne",
          "eventType": "course_a_pied",
          "name": "Ultra Trail La Mayenne",
          "numberOfRaceVariants": "unknown",
          "place": "Le Halage Mayenne",
          "registrationLink": "",
          "registrationStatus": "open",
        },
        {
          "beginning": 1791676800000,
          "city": "Saint-Hilaire-de-Clisson",
          "departementNumber": 44,
          "ending": 1791676800000,
          "eventLink": "https://www.timepulse.fr/evenements/voir/3359/les-foulees-hilairoises-saint-hilaire-de-clisson",
          "eventType": "course_a_pied",
          "name": "Les Foulées Hilairoises",
          "numberOfRaceVariants": "unknown",
          "place": "Stade de foot",
          "registrationLink": "",
          "registrationStatus": "open",
        },
        {
          "beginning": 1791676800000,
          "city": "Barbechat",
          "departementNumber": 44,
          "ending": 1791676800000,
          "eventLink": "https://www.timepulse.fr/evenements/voir/3499/barbecha-trail-2026-barbechat",
          "eventType": "course_a_pied",
          "name": "Barbecha’Trail 2026",
          "numberOfRaceVariants": "unknown",
          "place": "Salle du Bois Guillet",
          "registrationLink": "",
          "registrationStatus": "open",
        },
        {
          "beginning": 1792195200000,
          "city": "Le Cellier",
          "departementNumber": 44,
          "ending": 1792195200000,
          "eventLink": "https://www.timepulse.fr/evenements/voir/3350/les-foulees-siffait-le-cellier",
          "eventType": "course_a_pied",
          "name": "Les Foulées Siffait",
          "numberOfRaceVariants": "unknown",
          "place": "Complexe sportif - rue de Langförden",
          "registrationLink": "",
          "registrationStatus": "open",
        },
        {
          "beginning": 1792281600000,
          "city": "La Remaudière",
          "departementNumber": 44,
          "ending": 1792281600000,
          "eventLink": "https://www.timepulse.fr/evenements/voir/3311/rrx-rem-run-experience-la-remaudiere-44-la-remaudiere",
          "eventType": "course_a_pied",
          "name": "RRX Rem Run Expérience - La Remaudière (44)",
          "numberOfRaceVariants": "unknown",
          "place": "MAIRIE - LA REMAUDIERE",
          "registrationLink": "",
          "registrationStatus": "open",
        },
        {
          "beginning": 1792281600000,
          "city": "Orléans",
          "departementNumber": 45,
          "ending": 1792281600000,
          "eventLink": "https://www.timepulse.fr/calendrier/voir/3324/courses-de-l-indien-edition-2026-50e-edition-orleans",
          "eventType": "course_a_pied",
          "name": "Courses de l'Indien - Edition 2026 (50e édition)",
          "numberOfRaceVariants": "unknown",
          "place": "Place Albert Camus",
          "registrationLink": "",
          "registrationStatus": "unknown",
        },
        {
          "beginning": 1792281600000,
          "city": "La Chapelle-sur-Erdre",
          "departementNumber": 44,
          "ending": 1792281600000,
          "eventLink": "https://www.timepulse.fr/evenements/voir/3418/ouaga-sur-erdre-2026-la-chapelle-sur-erdre",
          "eventType": "course_a_pied",
          "name": "OUAGA SUR ERDRE 2026",
          "numberOfRaceVariants": "unknown",
          "place": "Complexe sportif du Buisson de la GROLLE",
          "registrationLink": "",
          "registrationStatus": "open",
        },
        {
          "beginning": 1792281600000,
          "city": "Saint-Nazaire",
          "departementNumber": 44,
          "ending": 1792281600000,
          "eventLink": "https://www.timepulse.fr/evenements/voir/3457/foulees-nazairiennes-2026-saint-nazaire",
          "eventType": "course_a_pied",
          "name": "Foulées Nazairiennes 2026",
          "numberOfRaceVariants": "unknown",
          "place": "Gymnase CARNOT rue du Traict",
          "registrationLink": "",
          "registrationStatus": "open",
        },
        {
          "beginning": 1792281600000,
          "city": "Nantes",
          "departementNumber": 44,
          "ending": 1792281600000,
          "eventLink": "https://www.timepulse.fr/evenements/voir/3477/triathlon-de-nantes-nantes",
          "eventType": "triathlon",
          "name": "Triathlon de Nantes",
          "numberOfRaceVariants": "unknown",
          "place": "Piscine Léo Lagrange, Allée de l'Île Gloriette",
          "registrationLink": "",
          "registrationStatus": "open",
        },
        {
          "beginning": 1792886400000,
          "city": "Cholet",
          "departementNumber": 49,
          "ending": 1792886400000,
          "eventLink": "https://www.timepulse.fr/evenements/voir/3411/les-foulees-choletaises-cholet",
          "eventType": "course_a_pied",
          "name": "Les Foulées Choletaises",
          "numberOfRaceVariants": "unknown",
          "place": "Salle Omnisports",
          "registrationLink": "",
          "registrationStatus": "open",
        },
        {
          "beginning": 1792886400000,
          "city": "Nantes",
          "departementNumber": 44,
          "ending": 1792886400000,
          "eventLink": "https://www.timepulse.fr/evenements/voir/3417/trail-urbain-nantais-100eme-tour-de-chantenay-nantes",
          "eventType": "course_a_pied",
          "name": "Trail Urbain Nantais - 100ème Tour de Chantenay",
          "numberOfRaceVariants": "unknown",
          "place": "Boulevard de la Liberté Nantes Chantenay",
          "registrationLink": "",
          "registrationStatus": "open",
        },
        {
          "beginning": 1793404800000,
          "city": "Saint-Géréon",
          "departementNumber": 44,
          "ending": 1793404800000,
          "eventLink": "https://www.timepulse.fr/evenements/voir/3452/la-555-by-go-trail-3-saint-gereon",
          "eventType": "course_a_pied",
          "name": "La 555 by Go'Trail (#3)",
          "numberOfRaceVariants": "unknown",
          "place": "Ecole du Gotha",
          "registrationLink": "",
          "registrationStatus": "open",
        },
        {
          "beginning": 1793404800000,
          "city": "Bouaye",
          "departementNumber": 44,
          "ending": 1793404800000,
          "eventLink": "https://www.timepulse.fr/evenements/voir/3486/trail-nocturne-bosceen-bouaye",
          "eventType": "course_a_pied",
          "name": "TRAIL NOCTURNE BOSCEEN",
          "numberOfRaceVariants": "unknown",
          "place": "Ensemble sportif René Gautier",
          "registrationLink": "",
          "registrationStatus": "open",
        },
      ]
    `);

    await browser.close();
  });
});
