import { readFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import { afterEach, describe, expect, it, vi } from 'vitest';
import { getBrowserPage } from '../../browser/browser.js';
import { mockFetch } from '../utils/mock-fetch.js';
import { listFutureEvents } from './scrapper.js';

describe('#klikego.listFutureEvents()', () => {
  afterEach(() => {
    vi.unstubAllGlobals();
  });

  it('should return list of all future events', async () => {
    const html = await readFile(
      resolve(__dirname, 'mocks/index.html'),
      'utf-8',
    );
    mockFetch([
      {
        match: 'https://www.klikego.com/v8/evenements/search.jsp?search=&geo=',
        format: 'text/html',
        response: html,
      },
    ]);
    const { browser, page } = await getBrowserPage();

    const list = await listFutureEvents(1, { page });
    expect(list).toMatchInlineSnapshot(`
      [
        {
          "beginning": 1778803200000,
          "city": "Guichen",
          "departementNumber": 35,
          "ending": 1788652800000,
          "eventLink": "https://www.klikego.com/inscription/stage-trail-en-suisse-normande-2026/running-course-a-pied/1773697515147-6",
          "eventType": "unknown",
          "name": "Stage Trail en Suisse normande",
          "numberOfRaceVariants": 1,
          "place": "unknown",
          "registrationLink": "",
          "registrationStatus": "unknown",
        },
        {
          "beginning": 1785542400000,
          "city": "Ploemeur",
          "departementNumber": 56,
          "ending": 1785628800000,
          "eventLink": "https://www.klikego.com/inscription/backyard-ultra-saint-jude-2026/running-course-a-pied/1779433585991-1",
          "eventType": "unknown",
          "name": "BACKYARD ULTRA Saint-Jude",
          "numberOfRaceVariants": 1,
          "place": "unknown",
          "registrationLink": "",
          "registrationStatus": "unknown",
        },
        {
          "beginning": 1785542400000,
          "city": "Agon coutainville",
          "departementNumber": 50,
          "ending": 1785628800000,
          "eventLink": "https://www.klikego.com/inscription/enduro-des-sables-2026/running-course-a-pied-marche-nordique/1497318881384-10",
          "eventType": "unknown",
          "name": "ENDURO des SABLES",
          "numberOfRaceVariants": 9,
          "place": "unknown",
          "registrationLink": "",
          "registrationStatus": "unknown",
        },
        {
          "beginning": 1785628800000,
          "city": "Erdeven",
          "departementNumber": 56,
          "ending": 1785628800000,
          "eventLink": "https://www.klikego.com/inscription/johannas-color-run-2026/running-course-a-pied/1559092823188-8",
          "eventType": "unknown",
          "name": "Johanna's Color Run",
          "numberOfRaceVariants": 1,
          "place": "unknown",
          "registrationLink": "",
          "registrationStatus": "unknown",
        },
        {
          "beginning": 1785628800000,
          "city": "La fresnais",
          "departementNumber": 35,
          "ending": 1785628800000,
          "eventLink": "https://www.klikego.com/inscription/la-fresnn-run-2026/course-a-pied-running/1774691656225-1",
          "eventType": "unknown",
          "name": "La Fresn'N Run",
          "numberOfRaceVariants": 3,
          "place": "unknown",
          "registrationLink": "",
          "registrationStatus": "unknown",
        },
        {
          "beginning": 1785628800000,
          "city": "Fougerolles du plessis",
          "departementNumber": 53,
          "ending": 1785628800000,
          "eventLink": "https://www.klikego.com/inscription/les-foulees-fougerollaises-2026/running-course-a-pied/1686604830451-8",
          "eventType": "unknown",
          "name": "Les foulées Fougerollaises",
          "numberOfRaceVariants": 4,
          "place": "unknown",
          "registrationLink": "",
          "registrationStatus": "unknown",
        },
        {
          "beginning": 1785628800000,
          "city": "St abraham",
          "departementNumber": 56,
          "ending": 1785628800000,
          "eventLink": "https://www.klikego.com/inscription/les-foulees-stephanoises-2026/running-course-a-pied/1529526473305-7",
          "eventType": "unknown",
          "name": "Les Foulées Stéphanoises",
          "numberOfRaceVariants": 2,
          "place": "unknown",
          "registrationLink": "",
          "registrationStatus": "unknown",
        },
        {
          "beginning": 1785628800000,
          "city": "St andre des eaux",
          "departementNumber": 22,
          "ending": 1785628800000,
          "eventLink": "https://www.klikego.com/inscription/marathon-st-andre-des-eaux--22630-2026/running-course-a-pied/1524255600254-7",
          "eventType": "unknown",
          "name": "MARATHON ST ANDRE DES EAUX 22630",
          "numberOfRaceVariants": 1,
          "place": "unknown",
          "registrationLink": "",
          "registrationStatus": "unknown",
        },
        {
          "beginning": 1785628800000,
          "city": "St sever calvados",
          "departementNumber": 14,
          "ending": 1785628800000,
          "eventLink": "https://www.klikego.com/inscription/trail-de-la-foret-de-saint-sever-2026/running-course-a-pied/1561506082592-14",
          "eventType": "unknown",
          "name": "Trail de la Forêt de Saint Sever",
          "numberOfRaceVariants": 3,
          "place": "unknown",
          "registrationLink": "",
          "registrationStatus": "unknown",
        },
        {
          "beginning": 1785628800000,
          "city": "Villefranche du perigord",
          "departementNumber": 24,
          "ending": 1785628800000,
          "eventLink": "https://www.klikego.com/inscription/trail-du-pays-du-chataignier-2026/course-a-pied-running/1652297007253-5",
          "eventType": "unknown",
          "name": "Trail du Pays du Châtaignier 2026",
          "numberOfRaceVariants": 2,
          "place": "unknown",
          "registrationLink": "",
          "registrationStatus": "unknown",
        },
        {
          "beginning": 1786060800000,
          "city": "La tranche sur mer",
          "departementNumber": 85,
          "ending": 1786060800000,
          "eventLink": "https://www.klikego.com/inscription/la-beach-run-tranchaise-2026/running-course-a-pied/1289363737972-23",
          "eventType": "unknown",
          "name": "LA BEACH RUN TRANCHAISE",
          "numberOfRaceVariants": 1,
          "place": "unknown",
          "registrationLink": "",
          "registrationStatus": "unknown",
        },
        {
          "beginning": 1786147200000,
          "city": "Riom es montagne",
          "departementNumber": 15,
          "ending": 1786147200000,
          "eventLink": "https://www.klikego.com/inscription/12eme-trail-des-6-burons-2026/course-a-pied-running/1417744126765-19",
          "eventType": "unknown",
          "name": "12ème Trail des 6 Burons",
          "numberOfRaceVariants": 4,
          "place": "unknown",
          "registrationLink": "",
          "registrationStatus": "unknown",
        },
        {
          "beginning": 1786147200000,
          "city": "Aubusson",
          "departementNumber": 23,
          "ending": 1786147200000,
          "eventLink": "https://www.klikego.com/inscription/corrida-pedestre-de-la-licorne-2026/running-course-a-pied/1743986785490-2",
          "eventType": "unknown",
          "name": "Corrida pédestre de la licorne",
          "numberOfRaceVariants": 2,
          "place": "unknown",
          "registrationLink": "",
          "registrationStatus": "unknown",
        },
        {
          "beginning": 1786147200000,
          "city": "Brasparts",
          "departementNumber": 29,
          "ending": 1786147200000,
          "eventLink": "https://www.klikego.com/inscription/les-foulees-de-brasparts-2026/course-a-pied-running/1529653089423-7",
          "eventType": "unknown",
          "name": "LES FOULÉES DE BRASPARTS",
          "numberOfRaceVariants": 2,
          "place": "unknown",
          "registrationLink": "",
          "registrationStatus": "unknown",
        },
        {
          "beginning": 1786147200000,
          "city": "St laurent du maroni",
          "departementNumber": 97,
          "ending": 1786147200000,
          "eventLink": "https://www.klikego.com/inscription/mini-marathon--saint-jeansaint-laurent-du-maroniles-foulees-de-lamitie-sportive-2026/running-course-a-pied/1782900274273-1",
          "eventType": "unknown",
          "name": "MINI MARATHON SAINT-JEAN/SAINT-LAURENT DU MARONILES FOULEES DE L'AMITIE SPORTIVE",
          "numberOfRaceVariants": 1,
          "place": "unknown",
          "registrationLink": "",
          "registrationStatus": "unknown",
        },
        {
          "beginning": 1786147200000,
          "city": "Penguily",
          "departementNumber": 22,
          "ending": 1786147200000,
          "eventLink": "https://www.klikego.com/inscription/trail-du-quiloury-2026/running-course-a-pied-marche-nordique/1717380072949-3",
          "eventType": "unknown",
          "name": "Trail du Quiloury",
          "numberOfRaceVariants": 4,
          "place": "unknown",
          "registrationLink": "",
          "registrationStatus": "unknown",
        },
        {
          "beginning": 1786233600000,
          "city": "Locmiquelic",
          "departementNumber": 56,
          "ending": 1786233600000,
          "eventLink": "https://www.klikego.com/inscription/foulees-des-langoustines-challenge-run-aventure-bro-an-oriant-2026/running-course-a-pied/1496620669711-8",
          "eventType": "unknown",
          "name": "FOULEES DES LANGOUSTINES - Challenge RUN AVENTURE BRO AN ORIANT 2026",
          "numberOfRaceVariants": 2,
          "place": "unknown",
          "registrationLink": "",
          "registrationStatus": "unknown",
        },
        {
          "beginning": 1786233600000,
          "city": "Montaignac st hippolyte",
          "departementNumber": 19,
          "ending": 1786233600000,
          "eventLink": "https://www.klikego.com/inscription/les-foulees-du-milhassou-2026/running-course-a-pied/1656531109697-5",
          "eventType": "unknown",
          "name": "Les Foulées du Milhassou 2026",
          "numberOfRaceVariants": 3,
          "place": "unknown",
          "registrationLink": "",
          "registrationStatus": "unknown",
        },
        {
          "beginning": 1786665600000,
          "city": "Pont l abbe",
          "departementNumber": 29,
          "ending": 1786665600000,
          "eventLink": "https://www.klikego.com/inscription/pont-labbe-urban-trail-2026/running-course-a-pied/1778797719471-1",
          "eventType": "unknown",
          "name": "Pont l'Abbé Urban Trail 2026",
          "numberOfRaceVariants": 2,
          "place": "unknown",
          "registrationLink": "",
          "registrationStatus": "unknown",
        },
        {
          "beginning": 1786752000000,
          "city": "Ste marie du mont",
          "departementNumber": 50,
          "ending": 1786752000000,
          "eventLink": "https://www.klikego.com/inscription/course-du-15-aout-2026/running-course-a-pied/1624668298530-6",
          "eventType": "unknown",
          "name": "Course du 15 août",
          "numberOfRaceVariants": 1,
          "place": "unknown",
          "registrationLink": "",
          "registrationStatus": "unknown",
        },
        {
          "beginning": 1786752000000,
          "city": "La chaux",
          "departementNumber": 25,
          "ending": 1786752000000,
          "eventLink": "https://www.klikego.com/inscription/foulees-saugettes-2026/running-course-a-pied/1433108543142-21",
          "eventType": "unknown",
          "name": "Foulées Saugettes 2026",
          "numberOfRaceVariants": 1,
          "place": "unknown",
          "registrationLink": "",
          "registrationStatus": "unknown",
        },
        {
          "beginning": 1786752000000,
          "city": "St geraud de corps",
          "departementNumber": 24,
          "ending": 1786752000000,
          "eventLink": "https://www.klikego.com/inscription/la-foulee-des-tourterelles-2026/running-course-a-pied/1650333998247-6",
          "eventType": "unknown",
          "name": "La Foulée des Tourterelles 2026",
          "numberOfRaceVariants": 3,
          "place": "unknown",
          "registrationLink": "",
          "registrationStatus": "unknown",
        },
        {
          "beginning": 1786752000000,
          "city": "Seilhac",
          "departementNumber": 19,
          "ending": 1786752000000,
          "eventLink": "https://www.klikego.com/inscription/seilhac-summer-run-2026/running-course-a-pied/1776993214196-1",
          "eventType": "unknown",
          "name": "Seilhac Summer Run",
          "numberOfRaceVariants": 2,
          "place": "unknown",
          "registrationLink": "",
          "registrationStatus": "unknown",
        },
        {
          "beginning": 1786752000000,
          "city": "Ychoux",
          "departementNumber": 40,
          "ending": 1786752000000,
          "eventLink": "https://www.klikego.com/inscription/trail-des-forges-ychoux-2026/running-course-a-pied/1741387871041-2",
          "eventType": "unknown",
          "name": "Trail des Forges Ychoux",
          "numberOfRaceVariants": 2,
          "place": "unknown",
          "registrationLink": "",
          "registrationStatus": "unknown",
        },
        {
          "beginning": 1786838400000,
          "city": "St pol de leon",
          "departementNumber": 29,
          "ending": 1786838400000,
          "eventLink": "https://www.klikego.com/inscription/larvor-saintpolitaine-2026/running-course-a-pied/1671003953876-6",
          "eventType": "unknown",
          "name": "L'Arvor Saintpolitaine",
          "numberOfRaceVariants": 2,
          "place": "unknown",
          "registrationLink": "",
          "registrationStatus": "unknown",
        },
        {
          "beginning": 1786838400000,
          "city": "La saline",
          "departementNumber": 97,
          "ending": 1786838400000,
          "eventLink": "https://www.klikego.com/inscription/parcours-dorientation-2026/running-course-a-pied/1783625839314-1",
          "eventType": "unknown",
          "name": "Parcours d'orientation",
          "numberOfRaceVariants": 2,
          "place": "unknown",
          "registrationLink": "",
          "registrationStatus": "unknown",
        },
        {
          "beginning": 1786838400000,
          "city": "St martin de fressengeas",
          "departementNumber": 24,
          "ending": 1786838400000,
          "eventLink": "https://www.klikego.com/inscription/trail-de-queue-dane-2026/running-course-a-pied/1622684601155-6",
          "eventType": "unknown",
          "name": "Trail de Queue D'Ane 2026",
          "numberOfRaceVariants": 4,
          "place": "unknown",
          "registrationLink": "",
          "registrationStatus": "unknown",
        },
        {
          "beginning": 1786838400000,
          "city": "St gilles les forets",
          "departementNumber": 87,
          "ending": 1786838400000,
          "eventLink": "https://www.klikego.com/inscription/trail-du-mont-gargan-2026/running-course-a-pied/1746145028683-2",
          "eventType": "unknown",
          "name": "Trail du Mont Gargan 2026",
          "numberOfRaceVariants": 1,
          "place": "unknown",
          "registrationLink": "",
          "registrationStatus": "unknown",
        },
        {
          "beginning": 1787356800000,
          "city": "Le cambout",
          "departementNumber": 22,
          "ending": 1787356800000,
          "eventLink": "https://www.klikego.com/inscription/la-viree-au-domaine-de-nounours-2026/running-course-a-pied/1433965577672-14",
          "eventType": "unknown",
          "name": "La Virée au Domaine de Nounours",
          "numberOfRaceVariants": 2,
          "place": "unknown",
          "registrationLink": "",
          "registrationStatus": "unknown",
        },
        {
          "beginning": 1787356800000,
          "city": "Penmarch",
          "departementNumber": 29,
          "ending": 1787356800000,
          "eventLink": "https://www.klikego.com/inscription/montee-du-phare-deckmuhl-2026/running-course-a-pied/1685770871621-4",
          "eventType": "unknown",
          "name": "Montée du Phare d'Eckmühl",
          "numberOfRaceVariants": 1,
          "place": "unknown",
          "registrationLink": "",
          "registrationStatus": "unknown",
        },
        {
          "beginning": 1787356800000,
          "city": "Pleubian",
          "departementNumber": 22,
          "ending": 1787356800000,
          "eventLink": "https://www.klikego.com/inscription/trail-de-lalgue-2026/running-course-a-pied-marche-nordique/1782109338804-1",
          "eventType": "unknown",
          "name": "Trail de l'algue 2026",
          "numberOfRaceVariants": 10,
          "place": "unknown",
          "registrationLink": "",
          "registrationStatus": "unknown",
        },
        {
          "beginning": 1787356800000,
          "city": "St francois longchamp",
          "departementNumber": 73,
          "ending": 1787356800000,
          "eventLink": "https://www.klikego.com/inscription/triathlon-de-la-madeleine-2026/triathlon/1699664782865-6",
          "eventType": "unknown",
          "name": "Triathlon de la Madeleine",
          "numberOfRaceVariants": 3,
          "place": "unknown",
          "registrationLink": "",
          "registrationStatus": "unknown",
        },
        {
          "beginning": 1787356800000,
          "city": "La ferte bernard",
          "departementNumber": 72,
          "ending": 1787443200000,
          "eventLink": "https://www.klikego.com/inscription/triathlon-de-la-ferte-bernard-2026/triathlon/1682975279042-5",
          "eventType": "unknown",
          "name": "Triathlon de la Ferté-Bernard 2026",
          "numberOfRaceVariants": 8,
          "place": "unknown",
          "registrationLink": "",
          "registrationStatus": "unknown",
        },
        {
          "beginning": 1787443200000,
          "city": "Madranges",
          "departementNumber": 19,
          "ending": 1787443200000,
          "eventLink": "https://www.klikego.com/inscription/foulees-de-madranges-2026/running-course-a-pied/1748553146887-2",
          "eventType": "unknown",
          "name": "Foulées de Madranges 2026",
          "numberOfRaceVariants": 3,
          "place": "unknown",
          "registrationLink": "",
          "registrationStatus": "unknown",
        },
        {
          "beginning": 1787443200000,
          "city": "Meslan",
          "departementNumber": 56,
          "ending": 1787443200000,
          "eventLink": "https://www.klikego.com/inscription/foulees-meslannaises-2026/running-course-a-pied/1653961052390-5",
          "eventType": "unknown",
          "name": "Foulées Meslannaises",
          "numberOfRaceVariants": 1,
          "place": "unknown",
          "registrationLink": "",
          "registrationStatus": "unknown",
        },
        {
          "beginning": 1787443200000,
          "city": "Le verdon sur mer",
          "departementNumber": 33,
          "ending": 1787443200000,
          "eventLink": "https://www.klikego.com/inscription/la-ronde-des-phares-2026/running-course-a-pied/1717106660656-3",
          "eventType": "unknown",
          "name": "La Ronde des Phares 2026",
          "numberOfRaceVariants": 3,
          "place": "unknown",
          "registrationLink": "",
          "registrationStatus": "unknown",
        },
        {
          "beginning": 1787443200000,
          "city": "Donzenac",
          "departementNumber": 19,
          "ending": 1787443200000,
          "eventLink": "https://www.klikego.com/inscription/la-ronde-du-four-2026/running-course-a-pied/1747097896945-2",
          "eventType": "unknown",
          "name": "La Ronde du Four 2026",
          "numberOfRaceVariants": 2,
          "place": "unknown",
          "registrationLink": "",
          "registrationStatus": "unknown",
        },
        {
          "beginning": 1787443200000,
          "city": "Plourivo",
          "departementNumber": 22,
          "ending": 1787443200000,
          "eventLink": "https://www.klikego.com/inscription/les-foulees-o2-lair-2026/running-course-a-pied/1643237107171-2",
          "eventType": "unknown",
          "name": "Les foulées O2 l'air",
          "numberOfRaceVariants": 3,
          "place": "unknown",
          "registrationLink": "",
          "registrationStatus": "unknown",
        },
        {
          "beginning": 1787443200000,
          "city": "Plomeur",
          "departementNumber": 29,
          "ending": 1787443200000,
          "eventLink": "https://www.klikego.com/inscription/marathon-des-etoiles-de-la-baie-2026/course-a-pied-running/1661660197943-8",
          "eventType": "unknown",
          "name": "MARATHON DES ÉTOILES DE LA BAIE",
          "numberOfRaceVariants": 1,
          "place": "unknown",
          "registrationLink": "",
          "registrationStatus": "unknown",
        },
        {
          "beginning": 1787443200000,
          "city": "Plouarzel",
          "departementNumber": 29,
          "ending": 1787443200000,
          "eventLink": "https://www.klikego.com/inscription/randos-u--vtt-gravel-marche---la-manche-atlantique--2026/cyclo/vtt/1752785676796-4",
          "eventType": "unknown",
          "name": "RANDOS U VTT - GRAVEL - MARCHE " La Manche Atlantique "",
          "numberOfRaceVariants": 2,
          "place": "unknown",
          "registrationLink": "",
          "registrationStatus": "unknown",
        },
        {
          "beginning": 1787443200000,
          "city": "Sene",
          "departementNumber": 56,
          "ending": 1787443200000,
          "eventLink": "https://www.klikego.com/inscription/run-in-sene-nature-2026/course-a-pied-running/1543709692306-8",
          "eventType": "unknown",
          "name": "Run in Séné Nature 2026",
          "numberOfRaceVariants": 4,
          "place": "unknown",
          "registrationLink": "",
          "registrationStatus": "unknown",
        },
        {
          "beginning": 1787443200000,
          "city": "Riec sur belon",
          "departementNumber": 29,
          "ending": 1787443200000,
          "eventLink": "https://www.klikego.com/inscription/trail-de-lhuitre-2026/running-course-a-pied/1777880501775-1",
          "eventType": "unknown",
          "name": "TRAIL DE L'HUITRE",
          "numberOfRaceVariants": 2,
          "place": "unknown",
          "registrationLink": "",
          "registrationStatus": "unknown",
        },
        {
          "beginning": 1787443200000,
          "city": "Peyrignac",
          "departementNumber": 24,
          "ending": 1787443200000,
          "eventLink": "https://www.klikego.com/inscription/trail-de-peyrignac-2026/running-course-a-pied/1747082851006-3",
          "eventType": "unknown",
          "name": "Trail de Peyrignac",
          "numberOfRaceVariants": 3,
          "place": "unknown",
          "registrationLink": "",
          "registrationStatus": "unknown",
        },
        {
          "beginning": 1787443200000,
          "city": "Inzinzac lochrist",
          "departementNumber": 56,
          "ending": 1787443200000,
          "eventLink": "https://www.klikego.com/inscription/trails-de-la-montagne-2026/course-a-pied-running/1776796331243-2",
          "eventType": "unknown",
          "name": "Trails de la montagne",
          "numberOfRaceVariants": 3,
          "place": "unknown",
          "registrationLink": "",
          "registrationStatus": "unknown",
        },
        {
          "beginning": 1787875200000,
          "city": "Plouay",
          "departementNumber": 56,
          "ending": 1787875200000,
          "eventLink": "https://www.klikego.com/inscription/urban-trail-2026/running-course-a-pied/1782607331698-1",
          "eventType": "unknown",
          "name": "Urban trail",
          "numberOfRaceVariants": 1,
          "place": "unknown",
          "registrationLink": "",
          "registrationStatus": "unknown",
        },
        {
          "beginning": 1787875200000,
          "city": "Ile d houat",
          "departementNumber": 56,
          "ending": 1788048000000,
          "eventLink": "https://www.klikego.com/inscription/le-tour-de-houat-2026/running-course-a-pied/1704950771660-2",
          "eventType": "unknown",
          "name": "Le Tour de Houat",
          "numberOfRaceVariants": 2,
          "place": "unknown",
          "registrationLink": "",
          "registrationStatus": "unknown",
        },
        {
          "beginning": 1787961600000,
          "city": "Pontmain",
          "departementNumber": 53,
          "ending": 1787961600000,
          "eventLink": "https://www.klikego.com/inscription/cross-de-la-foire-dautomne-2026/running-course-a-pied/1749784297019-2",
          "eventType": "unknown",
          "name": "Cross de la Foire d'Automne",
          "numberOfRaceVariants": 5,
          "place": "unknown",
          "registrationLink": "",
          "registrationStatus": "unknown",
        },
        {
          "beginning": 1787961600000,
          "city": "Guipavas",
          "departementNumber": 29,
          "ending": 1787961600000,
          "eventLink": "https://www.klikego.com/inscription/la-biskoulenn-2026/running-course-a-pied/1647992854676-5",
          "eventType": "unknown",
          "name": "La Biskoulenn",
          "numberOfRaceVariants": 2,
          "place": "unknown",
          "registrationLink": "",
          "registrationStatus": "unknown",
        },
        {
          "beginning": 1787961600000,
          "city": "Telgruc sur mer",
          "departementNumber": 29,
          "ending": 1787961600000,
          "eventLink": "https://www.klikego.com/inscription/la-trez-bellec-2026/running-course-a-pied/1743540715773-3",
          "eventType": "unknown",
          "name": "LA TREZ BELLEC",
          "numberOfRaceVariants": 3,
          "place": "unknown",
          "registrationLink": "",
          "registrationStatus": "unknown",
        },
        {
          "beginning": 1787961600000,
          "city": "Annesse et beaulieu",
          "departementNumber": 24,
          "ending": 1787961600000,
          "eventLink": "https://www.klikego.com/inscription/le-trail-dannesse-2026/running-course-a-pied/1654544826542-4",
          "eventType": "unknown",
          "name": "LE TRAIL D'ANNESSE 2026",
          "numberOfRaceVariants": 1,
          "place": "unknown",
          "registrationLink": "",
          "registrationStatus": "unknown",
        },
        {
          "beginning": 1787961600000,
          "city": "Cadalen",
          "departementNumber": 81,
          "ending": 1787961600000,
          "eventLink": "https://www.klikego.com/inscription/le-trail-du-1313-2026/running-course-a-pied/1715795807693-3",
          "eventType": "unknown",
          "name": "Le Trail du 1313 2026",
          "numberOfRaceVariants": 1,
          "place": "unknown",
          "registrationLink": "",
          "registrationStatus": "unknown",
        },
        {
          "beginning": 1787961600000,
          "city": "Langrune sur mer",
          "departementNumber": 14,
          "ending": 1787961600000,
          "eventLink": "https://www.klikego.com/inscription/les-foulees-gourmandes-2026/running-course-a-pied/1545792733497-8",
          "eventType": "unknown",
          "name": "Les Foulées Gourmandes",
          "numberOfRaceVariants": 1,
          "place": "unknown",
          "registrationLink": "",
          "registrationStatus": "unknown",
        },
        {
          "beginning": 1787961600000,
          "city": "Parigny",
          "departementNumber": 50,
          "ending": 1787961600000,
          "eventLink": "https://www.klikego.com/inscription/parigny-running-show-2026/running-course-a-pied/1726864032196-2",
          "eventType": "unknown",
          "name": "Parigny Running Show",
          "numberOfRaceVariants": 2,
          "place": "unknown",
          "registrationLink": "",
          "registrationStatus": "unknown",
        },
        {
          "beginning": 1787961600000,
          "city": "Ploufragan",
          "departementNumber": 22,
          "ending": 1787961600000,
          "eventLink": "https://www.klikego.com/inscription/plouftrail-de-la-maxi-gouet-2026/running-course-a-pied/1719017557913-3",
          "eventType": "unknown",
          "name": "Plouf'trail de la Maxi Gouët",
          "numberOfRaceVariants": 2,
          "place": "unknown",
          "registrationLink": "",
          "registrationStatus": "unknown",
        },
        {
          "beginning": 1787961600000,
          "city": "Plouay",
          "departementNumber": 56,
          "ending": 1787961600000,
          "eventLink": "https://www.klikego.com/inscription/randonnee-du-comite-des-fetes-de-plouay-2026/running-marche-nordique/1486906592795-20",
          "eventType": "unknown",
          "name": "Randonnée du Comité des fêtes de Plouay",
          "numberOfRaceVariants": "unknown",
          "place": "unknown",
          "registrationLink": "",
          "registrationStatus": "unknown",
        },
        {
          "beginning": 1787961600000,
          "city": "Tregunc",
          "departementNumber": 29,
          "ending": 1787961600000,
          "eventLink": "https://www.klikego.com/inscription/trail-de-saint-philibert-2026/running-course-a-pied/1566127531880-5",
          "eventType": "unknown",
          "name": "TRAIL DE SAINT-PHILIBERT",
          "numberOfRaceVariants": 1,
          "place": "unknown",
          "registrationLink": "",
          "registrationStatus": "unknown",
        },
        {
          "beginning": 1787961600000,
          "city": "St jean la poterie",
          "departementNumber": 56,
          "ending": 1787961600000,
          "eventLink": "https://www.klikego.com/inscription/trail-des-potians-episode-2-2026/running-course-a-pied/1741115948337-2",
          "eventType": "unknown",
          "name": "TRAIL DES POTIANS épisode 2",
          "numberOfRaceVariants": 6,
          "place": "unknown",
          "registrationLink": "",
          "registrationStatus": "unknown",
        },
        {
          "beginning": 1787961600000,
          "city": "Veigne",
          "departementNumber": 37,
          "ending": 1787961600000,
          "eventLink": "https://www.klikego.com/inscription/triathlon-de-veigne-edition-2026/triathlon/1740975965646-4",
          "eventType": "unknown",
          "name": "Triathlon de Veigné - Edition 2026",
          "numberOfRaceVariants": 4,
          "place": "unknown",
          "registrationLink": "",
          "registrationStatus": "unknown",
        },
        {
          "beginning": 1787961600000,
          "city": "Casteljaloux",
          "departementNumber": 47,
          "ending": 1788048000000,
          "eventLink": "https://www.klikego.com/inscription/triathlon-des-cadets-de-gascogne-2026/triathlon/1703648524449-5",
          "eventType": "unknown",
          "name": "TRIATHLON DES CADETS DE GASCOGNE 2026",
          "numberOfRaceVariants": 9,
          "place": "unknown",
          "registrationLink": "",
          "registrationStatus": "unknown",
        },
        {
          "beginning": 1788048000000,
          "city": "Clohars carnoet",
          "departementNumber": 29,
          "ending": 1788048000000,
          "eventLink": "https://www.klikego.com/inscription/16eme-triathlon-du-pays-de-quimperle-2026/triathlon/1329877266341-19",
          "eventType": "unknown",
          "name": "16ème Triathlon du Pays de Quimperlé",
          "numberOfRaceVariants": 4,
          "place": "unknown",
          "registrationLink": "",
          "registrationStatus": "unknown",
        },
        {
          "beginning": 1788048000000,
          "city": "Ergue gaberic",
          "departementNumber": 29,
          "ending": 1788048000000,
          "eventLink": "https://www.klikego.com/inscription/gravel-de-lodet-105km--60km--35km-2026/cyclo/vtt/1745366113769-2",
          "eventType": "unknown",
          "name": "Gravel de l'Odet 105km / 60km / 35km",
          "numberOfRaceVariants": 3,
          "place": "unknown",
          "registrationLink": "",
          "registrationStatus": "unknown",
        },
        {
          "beginning": 1788048000000,
          "city": "Drucat",
          "departementNumber": 80,
          "ending": 1788048000000,
          "eventLink": "https://www.klikego.com/inscription/la-cro-magnon-2026/course-a-pied-running/1767296761033-1",
          "eventType": "unknown",
          "name": "La Cro Magnon",
          "numberOfRaceVariants": 5,
          "place": "unknown",
          "registrationLink": "",
          "registrationStatus": "unknown",
        },
        {
          "beginning": 1788048000000,
          "city": "Domart en ponthieu",
          "departementNumber": 80,
          "ending": 1788048000000,
          "eventLink": "https://www.klikego.com/inscription/la-domartoise-2026/running-course-a-pied/1621924692918-10",
          "eventType": "unknown",
          "name": "LA DOMARTOISE",
          "numberOfRaceVariants": 5,
          "place": "unknown",
          "registrationLink": "",
          "registrationStatus": "unknown",
        },
        {
          "beginning": 1788048000000,
          "city": "Gourin",
          "departementNumber": 56,
          "ending": 1788048000000,
          "eventLink": "https://www.klikego.com/inscription/le-gouruntrail-2026/running-course-a-pied/1638121706046-6",
          "eventType": "unknown",
          "name": "Le Gouruntrail",
          "numberOfRaceVariants": 3,
          "place": "unknown",
          "registrationLink": "",
          "registrationStatus": "unknown",
        },
        {
          "beginning": 1788048000000,
          "city": "Rochechouart",
          "departementNumber": 87,
          "ending": 1788048000000,
          "eventLink": "https://www.klikego.com/inscription/les-10-km-vayres-rochechouart-2026/running-course-a-pied/1761079181557-2",
          "eventType": "unknown",
          "name": "Les 10 Km Vayres - Rochechouart",
          "numberOfRaceVariants": 1,
          "place": "unknown",
          "registrationLink": "",
          "registrationStatus": "unknown",
        },
        {
          "beginning": 1788048000000,
          "city": "Savenay",
          "departementNumber": 44,
          "ending": 1788048000000,
          "eventLink": "https://www.klikego.com/inscription/les-foulees-du-sillon-2026/running-course-a-pied/1430097349716-11",
          "eventType": "unknown",
          "name": "Les Foulées du Sillon 2026",
          "numberOfRaceVariants": 3,
          "place": "unknown",
          "registrationLink": "",
          "registrationStatus": "unknown",
        },
        {
          "beginning": 1788048000000,
          "city": "Aixe sur vienne",
          "departementNumber": 87,
          "ending": 1788048000000,
          "eventLink": "https://www.klikego.com/inscription/raid-bol-deau-2026/running-course-a-pied/1717782997203-3",
          "eventType": "unknown",
          "name": "RAID BOL D'EAU 2026",
          "numberOfRaceVariants": 4,
          "place": "unknown",
          "registrationLink": "",
          "registrationStatus": "unknown",
        },
        {
          "beginning": 1788048000000,
          "city": "Treffiagat",
          "departementNumber": 29,
          "ending": 1788048000000,
          "eventLink": "https://www.klikego.com/inscription/randonnee--course-libres-reves-de-marmouz-2026/running-course-a-pied/1722632170257-4",
          "eventType": "unknown",
          "name": "Randonnée & course libres Rêves de Marmouz",
          "numberOfRaceVariants": 1,
          "place": "unknown",
          "registrationLink": "",
          "registrationStatus": "unknown",
        },
        {
          "beginning": 1788048000000,
          "city": "Bourron marlotte",
          "departementNumber": 77,
          "ending": 1788048000000,
          "eventLink": "https://www.klikego.com/inscription/trail-de-bourron-marlotte-2026/running-course-a-pied/1778205266444-1",
          "eventType": "unknown",
          "name": "Trail de Bourron-Marlotte",
          "numberOfRaceVariants": 2,
          "place": "unknown",
          "registrationLink": "",
          "registrationStatus": "unknown",
        },
        {
          "beginning": 1788048000000,
          "city": "Chauvigny",
          "departementNumber": 86,
          "ending": 1788048000000,
          "eventLink": "https://www.klikego.com/inscription/trail-des-chateaux-2026/running-course-a-pied/1415523726020-9",
          "eventType": "unknown",
          "name": "Trail des Châteaux 2026",
          "numberOfRaceVariants": 4,
          "place": "unknown",
          "registrationLink": "",
          "registrationStatus": "unknown",
        },
        {
          "beginning": 1788048000000,
          "city": "Papenoo",
          "departementNumber": 98,
          "ending": 1788048000000,
          "eventLink": "https://www.klikego.com/inscription/trail-tahiti-papenoo-2026/running-course-a-pied-marche-nordique/1436987879178-27",
          "eventType": "unknown",
          "name": "TRAIL TAHITI PAPENOO 2026",
          "numberOfRaceVariants": 5,
          "place": "unknown",
          "registrationLink": "",
          "registrationStatus": "unknown",
        },
        {
          "beginning": 1788048000000,
          "city": "Carentan",
          "departementNumber": 50,
          "ending": 1788048000000,
          "eventLink": "https://www.klikego.com/inscription/triathlon-de-carentan-2026/triathlon/1580677317492-8",
          "eventType": "unknown",
          "name": "Triathlon de Carentan",
          "numberOfRaceVariants": 6,
          "place": "unknown",
          "registrationLink": "",
          "registrationStatus": "unknown",
        },
        {
          "beginning": 1788048000000,
          "city": "Ste adresse",
          "departementNumber": 76,
          "ending": 1788048000000,
          "eventLink": "https://www.klikego.com/inscription/triathlon-raid-du-cap-ste-adresse-2026/triathlon/1619593066063-13",
          "eventType": "unknown",
          "name": "Triathlon Raid du Cap Ste Adresse",
          "numberOfRaceVariants": 5,
          "place": "unknown",
          "registrationLink": "",
          "registrationStatus": "unknown",
        },
        {
          "beginning": 1788048000000,
          "city": "Bavent",
          "departementNumber": 14,
          "ending": 1788048000000,
          "eventLink": "https://www.klikego.com/inscription/urban-wild-bavent-2026/running-course-a-pied/1725333772884-4",
          "eventType": "unknown",
          "name": "URBAN WILD BAVENT",
          "numberOfRaceVariants": 2,
          "place": "unknown",
          "registrationLink": "",
          "registrationStatus": "unknown",
        },
        {
          "beginning": 1788566400000,
          "city": "Kernevel",
          "departementNumber": 29,
          "ending": 1788566400000,
          "eventLink": "https://www.klikego.com/inscription/24emes-foulees-kerneveloises-2026/running-course-a-pied/1531027253285-7",
          "eventType": "unknown",
          "name": "24èmes foulées kernéveloises",
          "numberOfRaceVariants": 1,
          "place": "unknown",
          "registrationLink": "",
          "registrationStatus": "unknown",
        },
        {
          "beginning": 1788566400000,
          "city": "Chateaulin",
          "departementNumber": 29,
          "ending": 1788566400000,
          "eventLink": "https://www.klikego.com/inscription/49eme-foulees-chateaulinoises-2026/running-course-a-pied/1496025007232-14",
          "eventType": "unknown",
          "name": "49ème Foulées Châteaulinoises",
          "numberOfRaceVariants": 2,
          "place": "unknown",
          "registrationLink": "",
          "registrationStatus": "unknown",
        },
        {
          "beginning": 1788566400000,
          "city": "St agathon",
          "departementNumber": 22,
          "ending": 1788566400000,
          "eventLink": "https://www.klikego.com/inscription/la-corridoeuf-2026/running-course-a-pied/1689804697914-7",
          "eventType": "unknown",
          "name": "La Corrid'Oeuf",
          "numberOfRaceVariants": 1,
          "place": "unknown",
          "registrationLink": "",
          "registrationStatus": "unknown",
        },
        {
          "beginning": 1788566400000,
          "city": "Pontivy",
          "departementNumber": 56,
          "ending": 1788566400000,
          "eventLink": "https://www.klikego.com/inscription/la-corrida-de-pontivy-2026/running-course-a-pied/1718231947073-2",
          "eventType": "unknown",
          "name": "La corrida de Pontivy",
          "numberOfRaceVariants": 2,
          "place": "unknown",
          "registrationLink": "",
          "registrationStatus": "unknown",
        },
        {
          "beginning": 1788566400000,
          "city": "La baule escoublac",
          "departementNumber": 44,
          "ending": 1788566400000,
          "eventLink": "https://www.klikego.com/inscription/la-course-au-homard-2026/running-course-a-pied/1781750639650-1",
          "eventType": "unknown",
          "name": "La course au homard",
          "numberOfRaceVariants": 3,
          "place": "unknown",
          "registrationLink": "",
          "registrationStatus": "unknown",
        },
        {
          "beginning": 1788566400000,
          "city": "La bosse de bretagne",
          "departementNumber": 35,
          "ending": 1788566400000,
          "eventLink": "https://www.klikego.com/inscription/la-grande-bosse-21km--la-petite-bosse-10km-2026/running-course-a-pied/1427507090682-24",
          "eventType": "unknown",
          "name": "La Grande Bosse 21km & la Petite Bosse 10km",
          "numberOfRaceVariants": 2,
          "place": "unknown",
          "registrationLink": "",
          "registrationStatus": "unknown",
        },
        {
          "beginning": 1788566400000,
          "city": "Allassac",
          "departementNumber": 19,
          "ending": 1788566400000,
          "eventLink": "https://www.klikego.com/inscription/les-foulees-de-la-tour-2026/running-course-a-pied/1693081209668-9",
          "eventType": "unknown",
          "name": "Les Foulées de la Tour",
          "numberOfRaceVariants": 2,
          "place": "unknown",
          "registrationLink": "",
          "registrationStatus": "unknown",
        },
        {
          "beginning": 1788566400000,
          "city": "Montreuil le gast",
          "departementNumber": 35,
          "ending": 1788566400000,
          "eventLink": "https://www.klikego.com/inscription/rural-trail-des-foulees-de-la-rosiere-2026/running-course-a-pied/1653540626177-7",
          "eventType": "unknown",
          "name": "Rural Trail des Foulées de la Rosière",
          "numberOfRaceVariants": 2,
          "place": "unknown",
          "registrationLink": "",
          "registrationStatus": "unknown",
        },
        {
          "beginning": 1788566400000,
          "city": "Tregueux",
          "departementNumber": 22,
          "ending": 1788566400000,
          "eventLink": "https://www.klikego.com/inscription/trail-de-la-vallee-de-lurne-2026/running-course-a-pied/1663749929985-9",
          "eventType": "unknown",
          "name": "Trail de la vallée de l'Urne",
          "numberOfRaceVariants": 5,
          "place": "unknown",
          "registrationLink": "",
          "registrationStatus": "unknown",
        },
        {
          "beginning": 1788566400000,
          "city": "Trevou treguignec",
          "departementNumber": 22,
          "ending": 1788566400000,
          "eventLink": "https://www.klikego.com/inscription/trail-de-la-vallee-du-bois-riou-2026/running-course-a-pied/1780645915872-1",
          "eventType": "unknown",
          "name": "Trail de la vallée du Bois Riou",
          "numberOfRaceVariants": 1,
          "place": "unknown",
          "registrationLink": "",
          "registrationStatus": "unknown",
        },
        {
          "beginning": 1788566400000,
          "city": "Châteaubourg",
          "departementNumber": 35,
          "ending": 1788566400000,
          "eventLink": "https://www.klikego.com/inscription/trail-urbain-de-chateaubourg-2026/running-course-a-pied/jceb_1353799516527-12",
          "eventType": "unknown",
          "name": "Trail Urbain de Châteaubourg",
          "numberOfRaceVariants": 5,
          "place": "unknown",
          "registrationLink": "",
          "registrationStatus": "unknown",
        },
        {
          "beginning": 1788566400000,
          "city": "Brest",
          "departementNumber": 29,
          "ending": 1788652800000,
          "eventLink": "https://www.klikego.com/inscription/trizef-triathlon-2026-2eme-edition/triathlon/1771306287932-1",
          "eventType": "unknown",
          "name": "Trizef Triathlon 2026 - 2ème édition",
          "numberOfRaceVariants": 4,
          "place": "unknown",
          "registrationLink": "",
          "registrationStatus": "unknown",
        },
        {
          "beginning": 1788652800000,
          "city": "Paris 16eme arrondissement",
          "departementNumber": 75,
          "ending": 1788652800000,
          "eventLink": "https://www.klikego.com/inscription/10km-hexagone-trocadero-2026/running-course-a-pied/1724195398568-2",
          "eventType": "unknown",
          "name": "10km Hexagone Trocadéro",
          "numberOfRaceVariants": 1,
          "place": "unknown",
          "registrationLink": "",
          "registrationStatus": "unknown",
        },
        {
          "beginning": 1788652800000,
          "city": "Angers",
          "departementNumber": 49,
          "ending": 1788652800000,
          "eventLink": "https://www.klikego.com/inscription/10km-run-despoir-2026/running-course-a-pied/1768252386841-1",
          "eventType": "unknown",
          "name": "10km Run d'espoir",
          "numberOfRaceVariants": 1,
          "place": "unknown",
          "registrationLink": "",
          "registrationStatus": "unknown",
        },
        {
          "beginning": 1788652800000,
          "city": "Ernee",
          "departementNumber": 53,
          "ending": 1788652800000,
          "eventLink": "https://www.klikego.com/inscription/5-et-10km-de-la-st-gregoire-2026/running-course-a-pied/1686604830451-7",
          "eventType": "unknown",
          "name": "5 et 10km de la st Grégoire",
          "numberOfRaceVariants": 4,
          "place": "unknown",
          "registrationLink": "",
          "registrationStatus": "unknown",
        },
        {
          "beginning": 1788652800000,
          "city": "Lacaune",
          "departementNumber": 81,
          "ending": 1788652800000,
          "eventLink": "https://www.klikego.com/inscription/charcutrails-2026/running-course-a-pied/1758051819634-1",
          "eventType": "unknown",
          "name": "CHARCU'TRAILS",
          "numberOfRaceVariants": 3,
          "place": "unknown",
          "registrationLink": "",
          "registrationStatus": "unknown",
        },
        {
          "beginning": 1788652800000,
          "city": "Carignan de bordeaux",
          "departementNumber": 33,
          "ending": 1788652800000,
          "eventLink": "https://www.klikego.com/inscription/courir-a-carignan-2026/running-course-a-pied/1681848760467-4",
          "eventType": "unknown",
          "name": "Courir à Carignan 2026",
          "numberOfRaceVariants": 3,
          "place": "unknown",
          "registrationLink": "",
          "registrationStatus": "unknown",
        },
        {
          "beginning": 1788652800000,
          "city": "Guemene sur scorff",
          "departementNumber": 56,
          "ending": 1788652800000,
          "eventLink": "https://www.klikego.com/inscription/course-du-coeur-premiere-edition-5-km-2026/running-course-a-pied/1774946889808-1",
          "eventType": "unknown",
          "name": "COURSE DU COEUR - Première édition - 5 Km",
          "numberOfRaceVariants": 1,
          "place": "unknown",
          "registrationLink": "",
          "registrationStatus": "unknown",
        },
        {
          "beginning": 1788652800000,
          "city": "Quimper",
          "departementNumber": 29,
          "ending": 1788652800000,
          "eventLink": "https://www.klikego.com/inscription/foulees-de-menfouest-2026/running-course-a-pied/1495425678076-7",
          "eventType": "unknown",
          "name": "Foulées de Menfouest",
          "numberOfRaceVariants": 2,
          "place": "unknown",
          "registrationLink": "",
          "registrationStatus": "unknown",
        },
        {
          "beginning": 1788652800000,
          "city": "Santec",
          "departementNumber": 29,
          "ending": 1788652800000,
          "eventLink": "https://www.klikego.com/inscription/larmor-trail-santec-2026/running-course-a-pied/1623204318528-6",
          "eventType": "unknown",
          "name": "L'Armor Trail Santec",
          "numberOfRaceVariants": 5,
          "place": "unknown",
          "registrationLink": "",
          "registrationStatus": "unknown",
        },
        {
          "beginning": 1788652800000,
          "city": "Brie",
          "departementNumber": 16,
          "ending": 1788652800000,
          "eventLink": "https://www.klikego.com/inscription/la-braconienne-briaude-2026/running-course-a-pied/1776385987476-1",
          "eventType": "unknown",
          "name": "La braconienne Briaude",
          "numberOfRaceVariants": 4,
          "place": "unknown",
          "registrationLink": "",
          "registrationStatus": "unknown",
        },
        {
          "beginning": 1788652800000,
          "city": "St denis les bourg",
          "departementNumber": 1,
          "ending": 1788652800000,
          "eventLink": "https://www.klikego.com/inscription/la-color-run-des-crampo-nez-2026/running-course-a-pied/1775865885864-1",
          "eventType": "unknown",
          "name": "La Color Run des Cramp'O Nez",
          "numberOfRaceVariants": 1,
          "place": "unknown",
          "registrationLink": "",
          "registrationStatus": "unknown",
        },
        {
          "beginning": 1788652800000,
          "city": "La chevroliere",
          "departementNumber": 44,
          "ending": 1788652800000,
          "eventLink": "https://www.klikego.com/inscription/la-guibroul-2026/running-course-a-pied/1754425569405-3",
          "eventType": "unknown",
          "name": "La Guib'Roul",
          "numberOfRaceVariants": 1,
          "place": "unknown",
          "registrationLink": "",
          "registrationStatus": "unknown",
        },
        {
          "beginning": 1788652800000,
          "city": "La chapelle d aligne",
          "departementNumber": 72,
          "ending": 1788652800000,
          "eventLink": "https://www.klikego.com/inscription/la-guibollrun-2026/running-course-a-pied/1579734410853-8",
          "eventType": "unknown",
          "name": "La Guiboll'run",
          "numberOfRaceVariants": 6,
          "place": "unknown",
          "registrationLink": "",
          "registrationStatus": "unknown",
        },
        {
          "beginning": 1788652800000,
          "city": "Ste helene",
          "departementNumber": 56,
          "ending": 1788652800000,
          "eventLink": "https://www.klikego.com/inscription/la-santez-helen-la-course-nature-de-la-ria-detel-2026/running-course-a-pied/1485655279941-15",
          "eventType": "unknown",
          "name": "La Santez Helen La course nature de la ria d'Etel",
          "numberOfRaceVariants": 2,
          "place": "unknown",
          "registrationLink": "",
          "registrationStatus": "unknown",
        },
        {
          "beginning": 1788652800000,
          "city": "Chartres de bretagne",
          "departementNumber": 35,
          "ending": 1788652800000,
          "eventLink": "https://www.klikego.com/inscription/la-stellantis-run-2026/running-course-a-pied/1780688895761-1",
          "eventType": "unknown",
          "name": "La Stellantis Run",
          "numberOfRaceVariants": 3,
          "place": "unknown",
          "registrationLink": "",
          "registrationStatus": "unknown",
        },
        {
          "beginning": 1788652800000,
          "city": "Diesen",
          "departementNumber": 57,
          "ending": 1788652800000,
          "eventLink": "https://www.klikego.com/inscription/les-10-km-de-lavenir-edition-2026/running-course-a-pied/1717803804391-3",
          "eventType": "unknown",
          "name": "Les 10 km de l'Avenir - Edition 2026",
          "numberOfRaceVariants": 1,
          "place": "unknown",
          "registrationLink": "",
          "registrationStatus": "unknown",
        },
        {
          "beginning": 1788652800000,
          "city": "St thonan",
          "departementNumber": 29,
          "ending": 1788652800000,
          "eventLink": "https://www.klikego.com/inscription/les-boucles-de-saint-thonan-challenge-de-lelorn-2026/running-course-a-pied/1561498121416-12",
          "eventType": "unknown",
          "name": "Les Boucles de Saint-Thonan - Challenge de l'Elorn",
          "numberOfRaceVariants": 2,
          "place": "unknown",
          "registrationLink": "",
          "registrationStatus": "unknown",
        },
        {
          "beginning": 1788652800000,
          "city": "Val d ize",
          "departementNumber": 35,
          "ending": 1788652800000,
          "eventLink": "https://www.klikego.com/inscription/les-foulees-dize-2026/running-course-a-pied/1572788573194-7",
          "eventType": "unknown",
          "name": "LES FOULEES D'IZE 2026",
          "numberOfRaceVariants": 5,
          "place": "unknown",
          "registrationLink": "",
          "registrationStatus": "unknown",
        },
        {
          "beginning": 1788652800000,
          "city": "Cesson",
          "departementNumber": 77,
          "ending": 1788652800000,
          "eventLink": "https://www.klikego.com/inscription/les-foulees-de-la-foret-de-breviande-2026/running-course-a-pied/1430291346020-13",
          "eventType": "unknown",
          "name": "Les Foulées de la Forêt de Bréviande",
          "numberOfRaceVariants": 3,
          "place": "unknown",
          "registrationLink": "",
          "registrationStatus": "unknown",
        },
        {
          "beginning": 1788652800000,
          "city": "Paris 16eme arrondissement",
          "departementNumber": 75,
          "ending": 1788652800000,
          "eventLink": "https://www.klikego.com/inscription/paris-eglises-tour-2026/running-course-a-pied/1763593801187-1",
          "eventType": "unknown",
          "name": "Paris Églises Tour 2026",
          "numberOfRaceVariants": 1,
          "place": "unknown",
          "registrationLink": "",
          "registrationStatus": "unknown",
        },
        {
          "beginning": 1788652800000,
          "city": "Mur de bretagne",
          "departementNumber": 22,
          "ending": 1788652800000,
          "eventLink": "https://www.klikego.com/inscription/randonnee-gourmande-la-randeau-des-papilles-2026/course-a-pied-running/1745360127215-2",
          "eventType": "unknown",
          "name": "Randonnée Gourmande - La Rand'Eau des Papilles",
          "numberOfRaceVariants": 3,
          "place": "unknown",
          "registrationLink": "",
          "registrationStatus": "unknown",
        },
        {
          "beginning": 1788652800000,
          "city": "Vecquemont",
          "departementNumber": 80,
          "ending": 1788652800000,
          "eventLink": "https://www.klikego.com/inscription/run-and-bike-la-vecquemontoise-2026/triathlon/1743801130879-2",
          "eventType": "unknown",
          "name": "Run and Bike La Vecquemontoise",
          "numberOfRaceVariants": 3,
          "place": "unknown",
          "registrationLink": "",
          "registrationStatus": "unknown",
        },
        {
          "beginning": 1788652800000,
          "city": "Sens",
          "departementNumber": 89,
          "ending": 1788652800000,
          "eventLink": "https://www.klikego.com/inscription/run-sens-piwi-2026/running-course-a-pied/1748303371812-2",
          "eventType": "unknown",
          "name": "RUN SENS PIWI 2026",
          "numberOfRaceVariants": 1,
          "place": "unknown",
          "registrationLink": "",
          "registrationStatus": "unknown",
        },
        {
          "beginning": 1788652800000,
          "city": "Ploneour lanvern",
          "departementNumber": 29,
          "ending": 1788652800000,
          "eventLink": "https://www.klikego.com/inscription/sur-les-traces-des-moulins-de-ploneour-2026/running-course-a-pied/1706220220437-5",
          "eventType": "unknown",
          "name": "Sur les Traces Des Moulins de Plonéour",
          "numberOfRaceVariants": 1,
          "place": "unknown",
          "registrationLink": "",
          "registrationStatus": "unknown",
        },
        {
          "beginning": 1788652800000,
          "city": "Dompierre sur charente",
          "departementNumber": 17,
          "ending": 1788652800000,
          "eventLink": "https://www.klikego.com/inscription/trail-de-fontseche-2026/running-course-a-pied/1773451446403-1",
          "eventType": "unknown",
          "name": "Trail de Fontseche",
          "numberOfRaceVariants": 3,
          "place": "unknown",
          "registrationLink": "",
          "registrationStatus": "unknown",
        },
        {
          "beginning": 1788652800000,
          "city": "Gestel",
          "departementNumber": 56,
          "ending": 1788652800000,
          "eventLink": "https://www.klikego.com/inscription/trail-de-gestel-2026/running-course-a-pied/1470777014151-8",
          "eventType": "unknown",
          "name": "Trail de Gestel",
          "numberOfRaceVariants": 2,
          "place": "unknown",
          "registrationLink": "",
          "registrationStatus": "unknown",
        },
        {
          "beginning": 1788652800000,
          "city": "Sulniac",
          "departementNumber": 56,
          "ending": 1788652800000,
          "eventLink": "https://www.klikego.com/inscription/trail-de-lecole-ste-therese-2026/running-course-a-pied/1781508971357-1",
          "eventType": "unknown",
          "name": "Trail de l'Ecole Ste Therese",
          "numberOfRaceVariants": 2,
          "place": "unknown",
          "registrationLink": "",
          "registrationStatus": "unknown",
        },
        {
          "beginning": 1788652800000,
          "city": "St remy en mauges",
          "departementNumber": 49,
          "ending": 1788652800000,
          "eventLink": "https://www.klikego.com/inscription/trail-des-croquants-2026/running-course-a-pied/1551850936519-8",
          "eventType": "unknown",
          "name": "Trail des Croquants",
          "numberOfRaceVariants": 6,
          "place": "unknown",
          "registrationLink": "",
          "registrationStatus": "unknown",
        },
        {
          "beginning": 1788652800000,
          "city": "Abjat sur bandiat",
          "departementNumber": 24,
          "ending": 1788652800000,
          "eventLink": "https://www.klikego.com/inscription/trail-du-bandiat-2026/running-course-a-pied/1688433500099-4",
          "eventType": "unknown",
          "name": "Trail du bandiat 2026",
          "numberOfRaceVariants": 4,
          "place": "unknown",
          "registrationLink": "",
          "registrationStatus": "unknown",
        },
        {
          "beginning": 1788652800000,
          "city": "Auray",
          "departementNumber": 56,
          "ending": 1788652800000,
          "eventLink": "https://www.klikego.com/inscription/tri-alre-race-saint-goustan-auray-2026/triathlon/1489906391862-10",
          "eventType": "unknown",
          "name": "TRI ALRE RACE - Saint Goustan Auray",
          "numberOfRaceVariants": 1,
          "place": "unknown",
          "registrationLink": "",
          "registrationStatus": "unknown",
        },
        {
          "beginning": 1788652800000,
          "city": "Caen",
          "departementNumber": 14,
          "ending": 1788652800000,
          "eventLink": "https://www.klikego.com/inscription/triathlon-de-caen-2026/triathlon/1513897436512-21",
          "eventType": "unknown",
          "name": "Triathlon de Caen 2026",
          "numberOfRaceVariants": 4,
          "place": "unknown",
          "registrationLink": "",
          "registrationStatus": "unknown",
        },
        {
          "beginning": 1788652800000,
          "city": "St gilles croix de vie",
          "departementNumber": 85,
          "ending": 1788652800000,
          "eventLink": "https://www.klikego.com/inscription/triathlon-de-saint-gilles-croix-de-vie-2026/triathlon/1644021780895-7",
          "eventType": "unknown",
          "name": "Triathlon de Saint-Gilles-Croix-de-Vie 2026",
          "numberOfRaceVariants": 5,
          "place": "unknown",
          "registrationLink": "",
          "registrationStatus": "unknown",
        },
        {
          "beginning": 1789171200000,
          "city": "Ambrieres les vallees",
          "departementNumber": 53,
          "ending": 1789171200000,
          "eventLink": "https://www.klikego.com/inscription/ambrieres-urban-trail-2026/running-course-a-pied/1559768009308-9",
          "eventType": "unknown",
          "name": "AMBRIERES URBAN TRAIL",
          "numberOfRaceVariants": 6,
          "place": "unknown",
          "registrationLink": "",
          "registrationStatus": "unknown",
        },
        {
          "beginning": 1789171200000,
          "city": "Le lion d angers",
          "departementNumber": 49,
          "ending": 1789171200000,
          "eventLink": "https://www.klikego.com/inscription/backyard-mils-205-2026/running-course-a-pied/1784066012251-1",
          "eventType": "unknown",
          "name": "Backyard MILS 205",
          "numberOfRaceVariants": 1,
          "place": "unknown",
          "registrationLink": "",
          "registrationStatus": "unknown",
        },
        {
          "beginning": 1789171200000,
          "city": "Savignac les eglises",
          "departementNumber": 24,
          "ending": 1789171200000,
          "eventLink": "https://www.klikego.com/inscription/causse-trail-2026/running-course-a-pied/1750897709640-2",
          "eventType": "unknown",
          "name": "Causse Trail 2026",
          "numberOfRaceVariants": 2,
          "place": "unknown",
          "registrationLink": "",
          "registrationStatus": "unknown",
        },
      ]
    `);

    await browser.close();
  });
});
