import { readFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import { describe, expect, it } from 'vitest';
import { getBrowserPage } from '../../browser/browser.js';
import { listFutureEvents } from './scrapper.js';

describe('#espaceCompetition.listFutureEvents()', () => {
  it('should return list of all future events', async () => {
    const html = await readFile(
      resolve(__dirname, 'mocks/index.html'),
      'utf-8',
    );
    const { browser, page } = await getBrowserPage({
      'https://www.espace-competition.com/index.php?module=accueil&action=agenda':
        {
          status: 200,
          contentType: 'text/html',
          body: html,
        },
    });

    const list = await listFutureEvents(1, { page });
    expect(list).toMatchInlineSnapshot(`
      [
        {
          "beginning": 1788566400000,
          "city": "DOMPIERRE SUR YON",
          "departementNumber": 85,
          "ending": 1788566400000,
          "eventLink": "https://dompierrecourseaventure.fr/",
          "eventType": "running",
          "name": "LA DOM'PIED'ROISE",
          "numberOfRaceVariants": 7,
          "place": "unknown",
          "registrationLink": "https://www.espace-competition.com/index.php?module=inscription&comp=3166",
          "registrationStatus": "open",
        },
        {
          "beginning": 1788652800000,
          "city": "OMBREE D'ANJOU",
          "departementNumber": 49,
          "ending": 1788652800000,
          "eventLink": "https://sites.google.com/site/triathlonpouance/triathlon/accueil-du-triathlon?authuser=0",
          "eventType": "triathlon",
          "name": "TRIATHLON DE POUANCE",
          "numberOfRaceVariants": 5,
          "place": "unknown",
          "registrationLink": "https://www.espace-competition.com/index.php?module=inscription&comp=3194",
          "registrationStatus": "open",
        },
        {
          "beginning": 1788652800000,
          "city": "BASSE GOULAINE",
          "departementNumber": 44,
          "ending": 1788652800000,
          "eventLink": "http://www.basse-goulaine.fr/",
          "eventType": "running",
          "name": "LES SENTIERS DE GOULAINE 2026",
          "numberOfRaceVariants": 4,
          "place": "unknown",
          "registrationLink": "https://www.espace-competition.com/index.php?module=inscription&comp=3176",
          "registrationStatus": "open",
        },
        {
          "beginning": 1788652800000,
          "city": "ECOUCHÉ LES VALLÉES",
          "departementNumber": 61,
          "ending": 1788652800000,
          "eventLink": "https://www.facebook.com/groups/4155814168077047/",
          "eventType": "poursuite_sur_terre",
          "name": "POURSUITE SUR TERRE - TRROISIEME ÉPREUVE DU TROPHÉE MAINE ANJOU ECOUCHE",
          "numberOfRaceVariants": 38,
          "place": "unknown",
          "registrationLink": "https://www.espace-competition.com/index.php?module=inscription&comp=3224",
          "registrationStatus": "not_open_yet",
        },
        {
          "beginning": 1789084800000,
          "city": "ECOUFLANT",
          "departementNumber": 49,
          "ending": 1789084800000,
          "eventLink": "http://lesfouleesdecouflant.sportsregions.fr/",
          "eventType": "running",
          "name": "LES FOULÉES D'ECOUFLANT",
          "numberOfRaceVariants": 3,
          "place": "unknown",
          "registrationLink": "https://www.espace-competition.com/index.php?module=inscription&comp=3097",
          "registrationStatus": "closed",
        },
        {
          "beginning": 1789171200000,
          "city": "MOULLERON LE CAPTIF",
          "departementNumber": 85,
          "ending": 1789171200000,
          "eventLink": "https://runinmouilleron.s2.yapla.com/fr/",
          "eventType": "running",
          "name": "COURSE AU JAMBON 2026",
          "numberOfRaceVariants": 8,
          "place": "unknown",
          "registrationLink": "https://www.espace-competition.com/index.php?module=inscription&comp=3191",
          "registrationStatus": "open",
        },
        {
          "beginning": 1789257600000,
          "city": "REZÉ",
          "departementNumber": 44,
          "ending": 1789257600000,
          "eventLink": "https://asbr-athle.fr/les-challenges-de-reze/",
          "eventType": "running",
          "name": "LES CHALLENGES DE REZÉ 2026",
          "numberOfRaceVariants": 7,
          "place": "unknown",
          "registrationLink": "https://www.espace-competition.com/index.php?module=inscription&comp=3123",
          "registrationStatus": "open",
        },
        {
          "beginning": 1789257600000,
          "city": "L'HUISSERIE",
          "departementNumber": 53,
          "ending": 1789257600000,
          "eventLink": "https://lhuisseriejogging.wordpress.com/",
          "eventType": "running",
          "name": "L’HUISS’RUN",
          "numberOfRaceVariants": 6,
          "place": "unknown",
          "registrationLink": "https://www.espace-competition.com/index.php?module=inscription&comp=3181",
          "registrationStatus": "open",
        },
        {
          "beginning": 1789257600000,
          "city": "LA FLÈCHE",
          "departementNumber": 72,
          "ending": 1789257600000,
          "eventLink": "http://www.la-fleche-triathlon.fr/",
          "eventType": "triathlon",
          "name": "CROSS TRIATHLON DE LA FLÈCHE",
          "numberOfRaceVariants": 8,
          "place": "unknown",
          "registrationLink": "https://www.espace-competition.com/index.php?module=inscription&comp=3201",
          "registrationStatus": "open",
        },
        {
          "beginning": 1789776000000,
          "city": "LE PLESSIS GRAMMOIRE",
          "departementNumber": 49,
          "ending": 1789776000000,
          "eventLink": "http://www.grammoirienne.fr/",
          "eventType": "running",
          "name": "LA GRAMMOIRIENNE 2026",
          "numberOfRaceVariants": 5,
          "place": "unknown",
          "registrationLink": "https://www.espace-competition.com/index.php?module=inscription&comp=3103",
          "registrationStatus": "open",
        },
        {
          "beginning": 1789862400000,
          "city": "MAYET",
          "departementNumber": 72,
          "ending": 1789862400000,
          "eventLink": "https://www.vma72.fr/traildelantenne.html#anchor-top",
          "eventType": "trail",
          "name": "TRAIL DE L'ANTENNE DE MAYET / ROTARY 21KM 12KM 5KM",
          "numberOfRaceVariants": 3,
          "place": "unknown",
          "registrationLink": "https://www.espace-competition.com/index.php?module=inscription&comp=3159",
          "registrationStatus": "open",
        },
        {
          "beginning": 1789862400000,
          "city": "VIHIERS",
          "departementNumber": 49,
          "ending": 1789862400000,
          "eventLink": "https://athlelysvihiersois.sportsregions.fr/",
          "eventType": "running",
          "name": "TRAIL LYS HAUT LAYON",
          "numberOfRaceVariants": 7,
          "place": "unknown",
          "registrationLink": "https://www.espace-competition.com/index.php?module=inscription&comp=3150",
          "registrationStatus": "open",
        },
        {
          "beginning": 1789862400000,
          "city": "NESMY",
          "departementNumber": 85,
          "ending": 1789862400000,
          "eventLink": "https://www.semimarathondenesmy.fr/",
          "eventType": "running",
          "name": "SEMI-MARATHON ET 10 KM DE NESMY",
          "numberOfRaceVariants": 8,
          "place": "unknown",
          "registrationLink": "https://www.espace-competition.com/index.php?module=inscription&comp=3154",
          "registrationStatus": "open",
        },
        {
          "beginning": 1789862400000,
          "city": "BEAUCOUZÉ",
          "departementNumber": 49,
          "ending": 1789862400000,
          "eventLink": "https://foulees-automne.jimdo.com/",
          "eventType": "running",
          "name": "LES FOULÉES D'AUTOMNE 2026",
          "numberOfRaceVariants": 8,
          "place": "unknown",
          "registrationLink": "https://www.espace-competition.com/index.php?module=inscription&comp=3193",
          "registrationStatus": "open",
        },
        {
          "beginning": 1790380800000,
          "city": "AUBIGNY-LES CLOUZEAUX",
          "departementNumber": 85,
          "ending": 1790380800000,
          "eventLink": "https://facebook.com/events/s/journee-des-prefous/1503813831473914/",
          "eventType": "trail",
          "name": "TRAIL DES PRÉFOUS",
          "numberOfRaceVariants": 2,
          "place": "unknown",
          "registrationLink": "https://www.espace-competition.com/index.php?module=inscription&comp=3204",
          "registrationStatus": "open",
        },
        {
          "beginning": 1790467200000,
          "city": "SCEAUX",
          "departementNumber": 92,
          "ending": 1790467200000,
          "eventLink": "https://www.viradeparcdesceaux.org/",
          "eventType": "running",
          "name": "COURSE DU SOUFFLE DE SCEAUX 2026",
          "numberOfRaceVariants": 7,
          "place": "unknown",
          "registrationLink": "https://www.espace-competition.com/index.php?module=inscription&comp=3155",
          "registrationStatus": "open",
        },
        {
          "beginning": 1790467200000,
          "city": "NOTRE DAME DE MONTS",
          "departementNumber": 85,
          "ending": 1790467200000,
          "eventLink": "https://www.espace-competition.com/www.cpndm.fr",
          "eventType": "running",
          "name": "LA MONTOISE",
          "numberOfRaceVariants": 5,
          "place": "unknown",
          "registrationLink": "https://www.espace-competition.com/index.php?module=inscription&comp=3111",
          "registrationStatus": "open",
        },
        {
          "beginning": 1790467200000,
          "city": "SAINT-LAMBERT-DU-LATTAY",
          "departementNumber": 49,
          "ending": 1790467200000,
          "eventLink": "https://courirenlayon.fr/",
          "eventType": "trail",
          "name": "TRAILS DU LAYON",
          "numberOfRaceVariants": 9,
          "place": "unknown",
          "registrationLink": "https://www.espace-competition.com/index.php?module=inscription&comp=3138",
          "registrationStatus": "open",
        },
      ]
    `);

    await browser.close();
  });
});
