import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { describe, expect, it } from 'vitest';
import { getBrowserPage } from '../../browser/browser.js';
import { listFutureEvents } from './scrapper.js';

describe('#espaceCompetition.listFutureEvents()', () => {
  it('should return list of all future events', async () => {
    const html = readFileSync(resolve(__dirname, 'mocks/index.html'), 'utf-8');
    const { browser, page } = await getBrowserPage({
      'https://www.espace-competition.com/index.php?module=accueil&action=agenda':
        {
          status: 200,
          contentType: 'text/html',
          body: html,
        },
    });

    const list = await listFutureEvents(1, { page });
    expect(list).toMatchInlineSnapshot(`
      [
        {
          "beginning": "2026-09-05",
          "city": "DOMPIERRE SUR YON",
          "departementNumber": 85,
          "ending": "2026-09-05",
          "eventLink": "https://dompierrecourseaventure.fr/",
          "eventType": "running",
          "name": "LA DOM'PIED'ROISE",
          "numberOfRaceVariants": 7,
          "place": "unknown",
          "registrationLink": "https://www.espace-competition.com/index.php?module=inscription&comp=3166",
          "registrationStatus": "open",
        },
        {
          "beginning": "2026-09-06",
          "city": "OMBREE D'ANJOU",
          "departementNumber": 49,
          "ending": "2026-09-06",
          "eventLink": "https://sites.google.com/site/triathlonpouance/triathlon/accueil-du-triathlon?authuser=0",
          "eventType": "triathlon",
          "name": "TRIATHLON DE POUANCE",
          "numberOfRaceVariants": 5,
          "place": "unknown",
          "registrationLink": "https://www.espace-competition.com/index.php?module=inscription&comp=3194",
          "registrationStatus": "open",
        },
        {
          "beginning": "2026-09-06",
          "city": "BASSE GOULAINE",
          "departementNumber": 44,
          "ending": "2026-09-06",
          "eventLink": "http://www.basse-goulaine.fr/",
          "eventType": "running",
          "name": "LES SENTIERS DE GOULAINE 2026",
          "numberOfRaceVariants": 4,
          "place": "unknown",
          "registrationLink": "https://www.espace-competition.com/index.php?module=inscription&comp=3176",
          "registrationStatus": "open",
        },
        {
          "beginning": "2026-09-06",
          "city": "FAYE L'ABBESSE",
          "departementNumber": 79,
          "ending": "2026-09-06",
          "eventLink": null,
          "eventType": "poursuite_sur_terre",
          "name": "FAYE L'ABBESSE 6EME MANCHE TROPHEE POITOU CHARENTES VENDEE",
          "numberOfRaceVariants": 17,
          "place": "unknown",
          "registrationLink": "https://www.espace-competition.com/index.php?module=inscription&comp=3208",
          "registrationStatus": "not_open_yet",
        },
        {
          "beginning": "2026-09-06",
          "city": "ECOUCHÉ LES VALLÉES",
          "departementNumber": 61,
          "ending": "2026-09-06",
          "eventLink": "https://www.facebook.com/groups/4155814168077047/",
          "eventType": "poursuite_sur_terre",
          "name": "POURSUITE SUR TERRE - TRROISIEME ÉPREUVE DU TROPHÉE MAINE ANJOU ECOUCHE",
          "numberOfRaceVariants": 38,
          "place": "unknown",
          "registrationLink": "https://www.espace-competition.com/index.php?module=inscription&comp=3224",
          "registrationStatus": "not_open_yet",
        },
        {
          "beginning": "2026-09-11",
          "city": "ECOUFLANT",
          "departementNumber": 49,
          "ending": "2026-09-11",
          "eventLink": "http://lesfouleesdecouflant.sportsregions.fr/",
          "eventType": "running",
          "name": "LES FOULÉES D'ECOUFLANT",
          "numberOfRaceVariants": 3,
          "place": "unknown",
          "registrationLink": "https://www.espace-competition.com/index.php?module=inscription&comp=3097",
          "registrationStatus": "closed",
        },
        {
          "beginning": "2026-09-12",
          "city": "MOULLERON LE CAPTIF",
          "departementNumber": 85,
          "ending": "2026-09-12",
          "eventLink": "https://runinmouilleron.s2.yapla.com/fr/",
          "eventType": "running",
          "name": "COURSE AU JAMBON 2026",
          "numberOfRaceVariants": 8,
          "place": "unknown",
          "registrationLink": "https://www.espace-competition.com/index.php?module=inscription&comp=3191",
          "registrationStatus": "open",
        },
        {
          "beginning": "2026-09-13",
          "city": "REZÉ",
          "departementNumber": 44,
          "ending": "2026-09-13",
          "eventLink": "https://asbr-athle.fr/les-challenges-de-reze/",
          "eventType": "running",
          "name": "LES CHALLENGES DE REZÉ 2026",
          "numberOfRaceVariants": 7,
          "place": "unknown",
          "registrationLink": "https://www.espace-competition.com/index.php?module=inscription&comp=3123",
          "registrationStatus": "open",
        },
        {
          "beginning": "2026-09-13",
          "city": "L'HUISSERIE",
          "departementNumber": 53,
          "ending": "2026-09-13",
          "eventLink": "https://lhuisseriejogging.wordpress.com/",
          "eventType": "running",
          "name": "L’HUISS’RUN",
          "numberOfRaceVariants": 6,
          "place": "unknown",
          "registrationLink": "https://www.espace-competition.com/index.php?module=inscription&comp=3181",
          "registrationStatus": "open",
        },
        {
          "beginning": "2026-09-13",
          "city": "LA FLÈCHE",
          "departementNumber": 72,
          "ending": "2026-09-13",
          "eventLink": "http://www.la-fleche-triathlon.fr/",
          "eventType": "triathlon",
          "name": "CROSS TRIATHLON DE LA FLÈCHE",
          "numberOfRaceVariants": 8,
          "place": "unknown",
          "registrationLink": "https://www.espace-competition.com/index.php?module=inscription&comp=3201",
          "registrationStatus": "open",
        },
        {
          "beginning": "2026-09-13",
          "city": "AVRILLE",
          "departementNumber": 49,
          "ending": "2026-09-13",
          "eventLink": null,
          "eventType": "running",
          "name": "LES FOULEES EN OR",
          "numberOfRaceVariants": 2,
          "place": "unknown",
          "registrationLink": "https://www.espace-competition.com/index.php?module=inscription&comp=3187",
          "registrationStatus": "open",
        },
        {
          "beginning": "2026-09-13",
          "city": "MONTAIGU-VENDEE",
          "departementNumber": 85,
          "ending": "2026-09-13",
          "eventLink": null,
          "eventType": "trail",
          "name": "TRAIL MONTAIGU VENDEE",
          "numberOfRaceVariants": 13,
          "place": "unknown",
          "registrationLink": "https://www.espace-competition.com/index.php?module=inscription&comp=3168",
          "registrationStatus": "open",
        },
        {
          "beginning": "2026-09-19",
          "city": "VOUTRÉ",
          "departementNumber": 53,
          "ending": "2026-09-19",
          "eventLink": null,
          "eventType": "trail",
          "name": "KABYLIE TRAIL",
          "numberOfRaceVariants": 4,
          "place": "unknown",
          "registrationLink": "https://www.espace-competition.com/index.php?module=inscription&comp=3153",
          "registrationStatus": "open",
        },
        {
          "beginning": "2026-09-19",
          "city": "LE PLESSIS GRAMMOIRE",
          "departementNumber": 49,
          "ending": "2026-09-19",
          "eventLink": "http://www.grammoirienne.fr/",
          "eventType": "running",
          "name": "LA GRAMMOIRIENNE 2026",
          "numberOfRaceVariants": 5,
          "place": "unknown",
          "registrationLink": "https://www.espace-competition.com/index.php?module=inscription&comp=3103",
          "registrationStatus": "open",
        },
        {
          "beginning": "2026-09-20",
          "city": "MAYET",
          "departementNumber": 72,
          "ending": "2026-09-20",
          "eventLink": "https://www.vma72.fr/traildelantenne.html#anchor-top",
          "eventType": "trail",
          "name": "TRAIL DE L'ANTENNE DE MAYET / ROTARY 21KM 12KM 5KM",
          "numberOfRaceVariants": 3,
          "place": "unknown",
          "registrationLink": "https://www.espace-competition.com/index.php?module=inscription&comp=3159",
          "registrationStatus": "open",
        },
        {
          "beginning": "2026-09-20",
          "city": "MAREUIL-SUR-LAY",
          "departementNumber": 85,
          "ending": "2026-09-20",
          "eventLink": null,
          "eventType": "trail",
          "name": "LE TRAIL “LA MAREUILLAISE”",
          "numberOfRaceVariants": 2,
          "place": "unknown",
          "registrationLink": "https://www.espace-competition.com/index.php?module=inscription&comp=3161",
          "registrationStatus": "open",
        },
        {
          "beginning": "2026-09-20",
          "city": "VIHIERS",
          "departementNumber": 49,
          "ending": "2026-09-20",
          "eventLink": "https://athlelysvihiersois.sportsregions.fr/",
          "eventType": "running",
          "name": "TRAIL LYS HAUT LAYON",
          "numberOfRaceVariants": 7,
          "place": "unknown",
          "registrationLink": "https://www.espace-competition.com/index.php?module=inscription&comp=3150",
          "registrationStatus": "open",
        },
        {
          "beginning": "2026-09-20",
          "city": "NESMY",
          "departementNumber": 85,
          "ending": "2026-09-20",
          "eventLink": "https://www.semimarathondenesmy.fr/",
          "eventType": "running",
          "name": "SEMI-MARATHON ET 10 KM DE NESMY",
          "numberOfRaceVariants": 8,
          "place": "unknown",
          "registrationLink": "https://www.espace-competition.com/index.php?module=inscription&comp=3154",
          "registrationStatus": "open",
        },
        {
          "beginning": "2026-09-20",
          "city": "BEAUCOUZÉ",
          "departementNumber": 49,
          "ending": "2026-09-20",
          "eventLink": "https://foulees-automne.jimdo.com/",
          "eventType": "running",
          "name": "LES FOULÉES D'AUTOMNE 2026",
          "numberOfRaceVariants": 8,
          "place": "unknown",
          "registrationLink": "https://www.espace-competition.com/index.php?module=inscription&comp=3193",
          "registrationStatus": "open",
        },
        {
          "beginning": "2026-09-26",
          "city": "ST GERMAIN D' ANXURE",
          "departementNumber": 53,
          "ending": "2026-09-27",
          "eventLink": "https://www.facebook.com/groups/4155814168077047/",
          "eventType": "poursuite_sur_terre",
          "name": "QUATRIÈME ÉPREUVES TROPHÉE MAINE ANJOU ST GERMAIN",
          "numberOfRaceVariants": 2,
          "place": "unknown",
          "registrationLink": "https://www.espace-competition.com/index.php?module=inscription&comp=3225",
          "registrationStatus": "not_open_yet",
        },
        {
          "beginning": "2026-09-26",
          "city": "SEGRE EN ANJOU BLEU",
          "departementNumber": 49,
          "ending": "2026-09-26",
          "eventLink": null,
          "eventType": "running",
          "name": "LA PETITE GEMMOISE 2026",
          "numberOfRaceVariants": 2,
          "place": "unknown",
          "registrationLink": "https://www.espace-competition.com/index.php?module=inscription&comp=3128",
          "registrationStatus": "open",
        },
        {
          "beginning": "2026-09-26",
          "city": "AUBIGNY-LES CLOUZEAUX",
          "departementNumber": 85,
          "ending": "2026-09-26",
          "eventLink": "https://facebook.com/events/s/journee-des-prefous/1503813831473914/",
          "eventType": "trail",
          "name": "TRAIL DES PRÉFOUS",
          "numberOfRaceVariants": 2,
          "place": "unknown",
          "registrationLink": "https://www.espace-competition.com/index.php?module=inscription&comp=3204",
          "registrationStatus": "open",
        },
        {
          "beginning": "2026-09-27",
          "city": "SAINTE GEMMES D’ANDIGNÉ",
          "departementNumber": 49,
          "ending": "2026-09-27",
          "eventLink": null,
          "eventType": "randonnee",
          "name": "RANDONNÉE GUSTATIVE LA PETITE GEMMOISE 2026",
          "numberOfRaceVariants": 0,
          "place": "unknown",
          "registrationLink": "https://www.espace-competition.com/index.php?module=inscription&comp=3129",
          "registrationStatus": "open",
        },
        {
          "beginning": "2026-09-27",
          "city": "LA CHAPELLE VICOMTESSE",
          "departementNumber": 41,
          "ending": "2026-09-27",
          "eventLink": null,
          "eventType": "poursuite_sur_terre",
          "name": "AUTO-POURSUITE KART CROSS CIRCUIT LA CHAPELLE VICOMTESSE CARITA",
          "numberOfRaceVariants": 15,
          "place": "unknown",
          "registrationLink": "https://www.espace-competition.com/index.php?module=inscription&comp=3117",
          "registrationStatus": "open",
        },
        {
          "beginning": "2026-09-27",
          "city": "LES MAGNILS-REIGNIERS",
          "departementNumber": 85,
          "ending": "2026-09-27",
          "eventLink": null,
          "eventType": "running",
          "name": "BIATHLON RUN",
          "numberOfRaceVariants": 4,
          "place": "unknown",
          "registrationLink": "https://www.espace-competition.com/index.php?module=inscription&comp=3174",
          "registrationStatus": "open",
        },
        {
          "beginning": "2026-09-27",
          "city": "SCEAUX",
          "departementNumber": 92,
          "ending": "2026-09-27",
          "eventLink": "https://www.viradeparcdesceaux.org/",
          "eventType": "running",
          "name": "COURSE DU SOUFFLE DE SCEAUX 2026",
          "numberOfRaceVariants": 7,
          "place": "unknown",
          "registrationLink": "https://www.espace-competition.com/index.php?module=inscription&comp=3155",
          "registrationStatus": "open",
        },
        {
          "beginning": "2026-09-27",
          "city": "NOTRE DAME DE MONTS",
          "departementNumber": 85,
          "ending": "2026-09-27",
          "eventLink": "https://www.espace-competition.com/www.cpndm.fr",
          "eventType": "running",
          "name": "LA MONTOISE",
          "numberOfRaceVariants": 5,
          "place": "unknown",
          "registrationLink": "https://www.espace-competition.com/index.php?module=inscription&comp=3111",
          "registrationStatus": "open",
        },
        {
          "beginning": "2026-09-27",
          "city": "SAINT-LAMBERT-DU-LATTAY",
          "departementNumber": 49,
          "ending": "2026-09-27",
          "eventLink": "https://courirenlayon.fr/",
          "eventType": "trail",
          "name": "TRAILS DU LAYON",
          "numberOfRaceVariants": 9,
          "place": "unknown",
          "registrationLink": "https://www.espace-competition.com/index.php?module=inscription&comp=3138",
          "registrationStatus": "open",
        },
        {
          "beginning": "2026-09-27",
          "city": "SAINT-VINCENT-SUR-GRAON",
          "departementNumber": 85,
          "ending": "2026-09-27",
          "eventLink": null,
          "eventType": "trail",
          "name": "LES FOULÉES DU GRAON",
          "numberOfRaceVariants": 5,
          "place": "unknown",
          "registrationLink": "https://www.espace-competition.com/index.php?module=inscription&comp=3169",
          "registrationStatus": "open",
        },
        {
          "beginning": "2026-10-04",
          "city": "ANGERS",
          "departementNumber": 49,
          "ending": "2026-10-04",
          "eventLink": null,
          "eventType": "course_d_orientation",
          "name": "COURSE D'ORIENTATAION 2026",
          "numberOfRaceVariants": 5,
          "place": "unknown",
          "registrationLink": "https://www.espace-competition.com/index.php?module=inscription&comp=3198",
          "registrationStatus": "open",
        },
        {
          "beginning": "2026-10-04",
          "city": "ROCHESERVIERE",
          "departementNumber": 85,
          "ending": "2026-10-04",
          "eventLink": "https://www.facebook.com/share/18N6fHYb9u/",
          "eventType": "trail",
          "name": "TRAIL DE LA SOURCE",
          "numberOfRaceVariants": 3,
          "place": "unknown",
          "registrationLink": "https://www.espace-competition.com/index.php?module=inscription&comp=3136",
          "registrationStatus": "open",
        },
        {
          "beginning": "2026-10-10",
          "city": "NOIRMOUTIER-EN-L'ÎLE",
          "departementNumber": 85,
          "ending": "2026-10-10",
          "eventLink": null,
          "eventType": "running",
          "name": "CROSS DÉPARTEMENTAL DES SAPEURS-POMPIERS DE LA VENDÉE",
          "numberOfRaceVariants": 1,
          "place": "unknown",
          "registrationLink": "https://www.espace-competition.com/index.php?module=inscription&comp=3210",
          "registrationStatus": "open",
        },
        {
          "beginning": "2026-10-10",
          "city": "SEGRE-EN-ANJOU BLEU (SEGRE)",
          "departementNumber": 49,
          "ending": "2026-10-10",
          "eventLink": "http://www.athletisme-esshautanjou.fr/",
          "eventType": "trail",
          "name": "TRAIL URBAIN DE SEGRE",
          "numberOfRaceVariants": 2,
          "place": "unknown",
          "registrationLink": "https://www.espace-competition.com/index.php?module=inscription&comp=3195",
          "registrationStatus": "open",
        },
        {
          "beginning": "2026-10-18",
          "city": "LE LUDE",
          "departementNumber": 72,
          "ending": "2026-10-18",
          "eventLink": "http://lesfouleesludoises.e-monsite.com/",
          "eventType": "running",
          "name": "LES FOULEES LUDOISES 2026 - 15EME EDITION",
          "numberOfRaceVariants": 2,
          "place": "unknown",
          "registrationLink": "https://www.espace-competition.com/index.php?module=inscription&comp=3107",
          "registrationStatus": "open",
        },
        {
          "beginning": "2026-10-18",
          "city": "LOIRE-AUTHION",
          "departementNumber": 49,
          "ending": "2026-10-18",
          "eventLink": "http://www.loire-authion.fr/course-nature-latitude/",
          "eventType": "running",
          "name": "LA’TITUDE ÉDITION 2026",
          "numberOfRaceVariants": 2,
          "place": "unknown",
          "registrationLink": "https://www.espace-competition.com/index.php?module=inscription&comp=3200",
          "registrationStatus": "open",
        },
        {
          "beginning": "2026-10-18",
          "city": "MOZÉ SUR LOUET",
          "departementNumber": 49,
          "ending": "2026-10-18",
          "eventLink": "https://lestracesdulouet.com/",
          "eventType": "running",
          "name": "LES TRACES DU LOUET",
          "numberOfRaceVariants": 9,
          "place": "unknown",
          "registrationLink": "https://www.espace-competition.com/index.php?module=inscription&comp=3125",
          "registrationStatus": "open",
        },
        {
          "beginning": "2026-10-24",
          "city": "SAINT JEAN DE LINIÈRES – SAINT LEGER DE LINIERES",
          "departementNumber": 49,
          "ending": "2026-10-24",
          "eventLink": "https://la-linieroise.sportsregions.fr/",
          "eventType": "running",
          "name": "13EME LINIÈROISE",
          "numberOfRaceVariants": 7,
          "place": "unknown",
          "registrationLink": "https://www.espace-competition.com/index.php?module=inscription&comp=3152",
          "registrationStatus": "closed",
        },
        {
          "beginning": "2026-10-25",
          "city": "LA ROCHE-SUR-YON",
          "departementNumber": 85,
          "ending": "2026-10-25",
          "eventLink": "https://larochesuryon.asptt.com/",
          "eventType": "running",
          "name": "LES FOULÉES BOURGADINES",
          "numberOfRaceVariants": 5,
          "place": "unknown",
          "registrationLink": "https://www.espace-competition.com/index.php?module=inscription&comp=3216",
          "registrationStatus": "open",
        },
        {
          "beginning": "2026-10-25",
          "city": "CRAON",
          "departementNumber": 53,
          "ending": "2026-10-25",
          "eventLink": "https://www.facebook.com/CraonNaturhallesTrail",
          "eventType": "trail",
          "name": "CRAON NATUR'HALLES TRAIL 2026",
          "numberOfRaceVariants": 9,
          "place": "unknown",
          "registrationLink": "https://www.espace-competition.com/index.php?module=inscription&comp=3219",
          "registrationStatus": "open",
        },
      ]
    `);

    await browser.close();
  });
});
