import { readFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import { afterEach, describe, expect, it, vi } from 'vitest';
import { getBrowserPage } from '../../browser/browser.js';
import { mockFetch } from '../utils/mock-fetch.js';
import { listFutureEvents } from './scrapper.js';

describe('#milesrepublic.listFutureEvents()', () => {
  afterEach(() => {
    vi.unstubAllGlobals();
  });

  it('should return list of all future events', async () => {
    const json = await readFile(
      resolve(__dirname, 'mocks/search.json'),
      'utf-8',
    );
    mockFetch([
      {
        match: 'https://search.milesrepublic.com/multi-search',
        format: 'application/json',
        response: json,
      },
    ]);

    const { browser } = await getBrowserPage();

    const list = await listFutureEvents(1);
    expect(list).toMatchInlineSnapshot(`
      [
        {
          "beginning": 1768604400000,
          "city": "Paris",
          "departementNumber": 75,
          "ending": 1796425200000,
          "eventLink": "https://fr.milesrepublic.com/event/2-miles-sri-chinmoy-7590",
          "eventType": "running",
          "name": "2 miles Sri Chinmoy",
          "numberOfRaceVariants": 1,
          "place": "unknown",
          "registrationLink": "",
          "registrationStatus": "open",
        },
        {
          "beginning": 1769986800000,
          "city": "Moûtiers",
          "departementNumber": 73,
          "ending": 1785621600000,
          "eventLink": "https://fr.milesrepublic.com/event/grand-raid-kiprun-3-vallees-moutiers-15342",
          "eventType": "trail",
          "name": "Grand Raid Kiprun 3 Vallées Moûtiers",
          "numberOfRaceVariants": 6,
          "place": "unknown",
          "registrationLink": "",
          "registrationStatus": "open",
        },
        {
          "beginning": 1773010800000,
          "city": "Velaux",
          "departementNumber": 13,
          "ending": 1809892800000,
          "eventLink": "https://fr.milesrepublic.com/event/rando-ste-propice-route-gravel-vtt-et-marche-15713",
          "eventType": "walk",
          "name": "Rando Ste Propice",
          "numberOfRaceVariants": 19,
          "place": "unknown",
          "registrationLink": "",
          "registrationStatus": "unknown",
        },
        {
          "beginning": 1777845600000,
          "city": "Saint-Jean-de-Monts",
          "departementNumber": 85,
          "ending": 1789369200000,
          "eventLink": "https://fr.milesrepublic.com/event/lindahls-pro-triathlon-series-12136",
          "eventType": "triathlon",
          "name": "Lindahls Pro+ Triathlon Séries",
          "numberOfRaceVariants": 2,
          "place": "unknown",
          "registrationLink": "",
          "registrationStatus": "unknown",
        },
        {
          "beginning": 1779598800000,
          "city": "Revest-les-Roches",
          "departementNumber": 6,
          "ending": 1785621600000,
          "eventLink": "https://fr.milesrepublic.com/event/la-verticale-haut-vial-5548",
          "eventType": "triathlon",
          "name": "La verticale Haut Vial",
          "numberOfRaceVariants": 3,
          "place": "unknown",
          "registrationLink": "",
          "registrationStatus": "open",
        },
        {
          "beginning": 1779962700000,
          "city": "Rosheim",
          "departementNumber": 67,
          "ending": 1790590500000,
          "eventLink": "https://fr.milesrepublic.com/event/les-foulees-des-4-portes-3037",
          "eventType": "running",
          "name": "Les foulées des 4 portes",
          "numberOfRaceVariants": 7,
          "place": "unknown",
          "registrationLink": "",
          "registrationStatus": "unknown",
        },
        {
          "beginning": 1780128000000,
          "city": "Château-Chinon(Ville)",
          "departementNumber": 58,
          "ending": 1794560400000,
          "eventLink": "https://fr.milesrepublic.com/event/morvan-oxygene-trail-2108",
          "eventType": "running",
          "name": "Morvan oxygène trail",
          "numberOfRaceVariants": 6,
          "place": "unknown",
          "registrationLink": "",
          "registrationStatus": "open",
        },
        {
          "beginning": 1780351200000,
          "city": "Peyrolles-en-Provence",
          "departementNumber": 13,
          "ending": 1789855200000,
          "eventLink": "https://fr.milesrepublic.com/event/mud-girl-provence-10158",
          "eventType": "fun",
          "name": "Mud girl Provence",
          "numberOfRaceVariants": 1,
          "place": "unknown",
          "registrationLink": "",
          "registrationStatus": "unknown",
        },
        {
          "beginning": 1780911000000,
          "city": "Cabourg",
          "departementNumber": 14,
          "ending": 1790460000000,
          "eventLink": "https://fr.milesrepublic.com/event/-lindahls-pro-triathlon-series-12724",
          "eventType": "triathlon",
          "name": " Lindahls Pro+ Triathlon Séries",
          "numberOfRaceVariants": 2,
          "place": "unknown",
          "registrationLink": "",
          "registrationStatus": "unknown",
        },
        {
          "beginning": 1781942400000,
          "city": "Peyrabout",
          "departementNumber": 23,
          "ending": 1790488800000,
          "eventLink": "https://fr.milesrepublic.com/event/l-enfer-vert-15328",
          "eventType": "other",
          "name": "L'enfer vert",
          "numberOfRaceVariants": 1,
          "place": "unknown",
          "registrationLink": "",
          "registrationStatus": "open",
        },
        {
          "beginning": 1782115200000,
          "city": "Albertville",
          "departementNumber": 73,
          "ending": 1786348800000,
          "eventLink": "https://fr.milesrepublic.com/event/la-monte-et-seche-10757",
          "eventType": "cycling",
          "name": "La Monte et sèche",
          "numberOfRaceVariants": 4,
          "place": "unknown",
          "registrationLink": "",
          "registrationStatus": "unknown",
        },
        {
          "beginning": 1782626400000,
          "city": "La Mézière",
          "departementNumber": 35,
          "ending": 1791183600000,
          "eventLink": "https://fr.milesrepublic.com/event/gravel-des-brasseurs-11986",
          "eventType": "cycling",
          "name": "LA Mez Bain",
          "numberOfRaceVariants": 2,
          "place": "unknown",
          "registrationLink": "",
          "registrationStatus": "unknown",
        },
        {
          "beginning": 1783116000000,
          "city": "Saint-Marcan",
          "departementNumber": 35,
          "ending": 1785621600000,
          "eventLink": "https://fr.milesrepublic.com/event/road-trip-de-broceliande-13945",
          "eventType": "walk",
          "name": "Road Trip de Brocéliande ",
          "numberOfRaceVariants": 1,
          "place": "unknown",
          "registrationLink": "",
          "registrationStatus": "unknown",
        },
        {
          "beginning": 1783202400000,
          "city": "Ambérieu-en-Bugey",
          "departementNumber": 1,
          "ending": 1792274400000,
          "eventLink": "https://fr.milesrepublic.com/event/bugey-night-racing-serie-9024",
          "eventType": "trail",
          "name": "Bugey night racing serie",
          "numberOfRaceVariants": 3,
          "place": "unknown",
          "registrationLink": "",
          "registrationStatus": "unknown",
        },
        {
          "beginning": 1785395100000,
          "city": "La Plagne-Tarentaise",
          "departementNumber": 73,
          "ending": 1785557100000,
          "eventLink": "https://fr.milesrepublic.com/event/la-6000d-la-plagne-2092",
          "eventType": "trail",
          "name": "La 6000D Trail de légende",
          "numberOfRaceVariants": 8,
          "place": "unknown",
          "registrationLink": "",
          "registrationStatus": "open",
        },
        {
          "beginning": 1785513600000,
          "city": "Pila",
          "departementNumber": 99,
          "ending": 1785571200000,
          "eventLink": "https://fr.milesrepublic.com/event/runthrough-trails-pila-15062",
          "eventType": "trail",
          "name": "Sugar Trail",
          "numberOfRaceVariants": 3,
          "place": "unknown",
          "registrationLink": "",
          "registrationStatus": "open",
        },
        {
          "beginning": 1785535200000,
          "city": "Aydius",
          "departementNumber": 64,
          "ending": 1785646800000,
          "eventLink": "https://fr.milesrepublic.com/event/trail-du-montagnon-8150",
          "eventType": "trail",
          "name": "Trail du montagnon",
          "numberOfRaceVariants": 3,
          "place": "unknown",
          "registrationLink": "",
          "registrationStatus": "open",
        },
        {
          "beginning": 1785556800000,
          "city": "La Condamine Chatelard",
          "departementNumber": 4,
          "ending": 1785565800000,
          "eventLink": "https://fr.milesrepublic.com/event/trail-des-forts-de-la-vallee-de-lubaye-17415",
          "eventType": "trail",
          "name": "Trail des Forts de la Vallée de l'Ubaye",
          "numberOfRaceVariants": 3,
          "place": "unknown",
          "registrationLink": "",
          "registrationStatus": "open",
        },
        {
          "beginning": 1785564000000,
          "city": "Valmeinier",
          "departementNumber": 73,
          "ending": 1785650400000,
          "eventLink": "https://fr.milesrepublic.com/event/enduro-series-coupe-de-france-enduro-vtt-and-vttae-valmeinier-10580",
          "eventType": "cycling",
          "name": "Enduro Series - Coupe de France Enduro VTT & VTTAE - Valmeinier",
          "numberOfRaceVariants": 0,
          "place": "unknown",
          "registrationLink": "",
          "registrationStatus": "open",
        },
        {
          "beginning": 1785567600000,
          "city": "Le Bourg-d'Oisans",
          "departementNumber": 38,
          "ending": 1785654000000,
          "eventLink": "https://fr.milesrepublic.com/event/trail-de-l-etendard-2134",
          "eventType": "trail",
          "name": "Trail de l'étendard",
          "numberOfRaceVariants": 4,
          "place": "unknown",
          "registrationLink": "",
          "registrationStatus": "open",
        },
        {
          "beginning": 1785567600000,
          "city": "Saint-Germain-du-Bel-Air",
          "departementNumber": 46,
          "ending": 1785567600000,
          "eventLink": "https://fr.milesrepublic.com/event/trail-du-ceou-2259",
          "eventType": "trail",
          "name": "Trail du Céou",
          "numberOfRaceVariants": 3,
          "place": "unknown",
          "registrationLink": "",
          "registrationStatus": "open",
        },
        {
          "beginning": 1785567600000,
          "city": "Orcières",
          "departementNumber": 5,
          "ending": 1785657600000,
          "eventLink": "https://fr.milesrepublic.com/event/les-trail-des-lacs-dorcieres-2539",
          "eventType": "trail",
          "name": "Les trail des lacs d'Orcières",
          "numberOfRaceVariants": 8,
          "place": "unknown",
          "registrationLink": "",
          "registrationStatus": "open",
        },
        {
          "beginning": 1785571200000,
          "city": "Blaesheim",
          "departementNumber": 67,
          "ending": 1785571200000,
          "eventLink": "https://fr.milesrepublic.com/event/loopsheim-17414",
          "eventType": "running",
          "name": "Loopsheim",
          "numberOfRaceVariants": 1,
          "place": "unknown",
          "registrationLink": "",
          "registrationStatus": "open",
        },
        {
          "beginning": 1785576600000,
          "city": "Deauville",
          "departementNumber": 14,
          "ending": 1785576600000,
          "eventLink": "https://fr.milesrepublic.com/event/stage-entrainement-eau-libre-et-triathlon-deauville-14089",
          "eventType": "other",
          "name": "STAGE ENTRAINEMENT EAU LIBRE ET TRIATHLON - Deauville",
          "numberOfRaceVariants": 0,
          "place": "unknown",
          "registrationLink": "",
          "registrationStatus": "unknown",
        },
        {
          "beginning": 1785587400000,
          "city": "Agon-Coutainville",
          "departementNumber": 50,
          "ending": 1785684900000,
          "eventLink": "https://fr.milesrepublic.com/event/enduro-des-sables-2493",
          "eventType": "running",
          "name": "Enduro des sables",
          "numberOfRaceVariants": 7,
          "place": "unknown",
          "registrationLink": "",
          "registrationStatus": "open",
        },
        {
          "beginning": 1785592800000,
          "city": "Nedde",
          "departementNumber": 987,
          "ending": 1785598200000,
          "eventLink": "https://fr.milesrepublic.com/event/la-course-des-2-ponts-2445",
          "eventType": "running",
          "name": "La course des 2 ponts",
          "numberOfRaceVariants": 5,
          "place": "unknown",
          "registrationLink": "",
          "registrationStatus": "open",
        },
        {
          "beginning": 1785592800000,
          "city": "Beaufort",
          "departementNumber": 73,
          "ending": 1785650400000,
          "eventLink": "https://fr.milesrepublic.com/event/trail-la-frison-roche-6692",
          "eventType": "trail",
          "name": "Trail la Frison Roche",
          "numberOfRaceVariants": 5,
          "place": "unknown",
          "registrationLink": "",
          "registrationStatus": "open",
        },
        {
          "beginning": 1785594600000,
          "city": "Saint-Pierre",
          "departementNumber": 4,
          "ending": 1785600000000,
          "eventLink": "https://fr.milesrepublic.com/event/les-foulees-semi-nocturne-de-la-ville-de-st-pierre-14131",
          "eventType": "running",
          "name": "Les foulées semi nocturne de la ville de st pierre",
          "numberOfRaceVariants": 2,
          "place": "unknown",
          "registrationLink": "",
          "registrationStatus": "open",
        },
        {
          "beginning": 1785596400000,
          "city": "Rubempré",
          "departementNumber": 80,
          "ending": 1785600000000,
          "eventLink": "https://fr.milesrepublic.com/event/les-boucles-rubempreennes-5537",
          "eventType": "running",
          "name": "Les boucles rubempréennes",
          "numberOfRaceVariants": 4,
          "place": "unknown",
          "registrationLink": "",
          "registrationStatus": "open",
        },
        {
          "beginning": 1785600000000,
          "city": "Vielmur-sur-Agout",
          "departementNumber": 81,
          "ending": 1785603600000,
          "eventLink": "https://fr.milesrepublic.com/event/la-ronde-cuquoise-2456",
          "eventType": "walk",
          "name": "La ronde cuquoise",
          "numberOfRaceVariants": 2,
          "place": "unknown",
          "registrationLink": "",
          "registrationStatus": "open",
        },
        {
          "beginning": 1785600000000,
          "city": "Surbourg",
          "departementNumber": 67,
          "ending": 1785600000000,
          "eventLink": "https://fr.milesrepublic.com/event/corrida-de-surbourg-9165",
          "eventType": "running",
          "name": "Corrida de surbourg	",
          "numberOfRaceVariants": 4,
          "place": "unknown",
          "registrationLink": "",
          "registrationStatus": "open",
        },
        {
          "beginning": 1785600000000,
          "city": "Plouhinec",
          "departementNumber": 56,
          "ending": 1785600000000,
          "eventLink": "https://fr.milesrepublic.com/event/course-nature-des-dunes-12184",
          "eventType": "trail",
          "name": "Course nature des dunes",
          "numberOfRaceVariants": 1,
          "place": "unknown",
          "registrationLink": "",
          "registrationStatus": "open",
        },
        {
          "beginning": 1785600000000,
          "city": "Treffiagat",
          "departementNumber": 29,
          "ending": 1785600000000,
          "eventLink": "https://fr.milesrepublic.com/event/la-course-des-sauveteurs-en-mer-16647",
          "eventType": "running",
          "name": "La Course Des Sauveteurs En Mer",
          "numberOfRaceVariants": 1,
          "place": "unknown",
          "registrationLink": "",
          "registrationStatus": "open",
        },
        {
          "beginning": 1785600000000,
          "city": "Velzic",
          "departementNumber": 15,
          "ending": 1785601800000,
          "eventLink": "https://fr.milesrepublic.com/event/trail-des-fontaines-de-velzic-17238",
          "eventType": "trail",
          "name": "Trail Des Fontaines De Velzic",
          "numberOfRaceVariants": 2,
          "place": "unknown",
          "registrationLink": "",
          "registrationStatus": "open",
        },
        {
          "beginning": 1785601800000,
          "city": "Saint Esteve",
          "departementNumber": 66,
          "ending": 1785601800000,
          "eventLink": "https://fr.milesrepublic.com/event/urban-trail-saint-esteve-17565",
          "eventType": "trail",
          "name": "Urban Trail Saint Esteve",
          "numberOfRaceVariants": 1,
          "place": "unknown",
          "registrationLink": "",
          "registrationStatus": "open",
        },
        {
          "beginning": 1785603600000,
          "city": "Ribes",
          "departementNumber": 7,
          "ending": 1785603600000,
          "eventLink": "https://fr.milesrepublic.com/event/semi-nocturne-de-ribes-16011",
          "eventType": "trail",
          "name": "Semi Nocturne De Ribes",
          "numberOfRaceVariants": 1,
          "place": "unknown",
          "registrationLink": "",
          "registrationStatus": "open",
        },
        {
          "beginning": 1785621600000,
          "city": "Vayrac",
          "departementNumber": 46,
          "ending": 1785621600000,
          "eventLink": "https://fr.milesrepublic.com/event/la-boucle-nature-de-l-ete-5556",
          "eventType": "running",
          "name": "La boucle nature de l'été",
          "numberOfRaceVariants": 1,
          "place": "unknown",
          "registrationLink": "",
          "registrationStatus": "unknown",
        },
        {
          "beginning": 1785621600000,
          "city": "Hagetmau",
          "departementNumber": 40,
          "ending": 1785621600000,
          "eventLink": "https://fr.milesrepublic.com/event/les-foulees-de-la-perle-de-la-chalosse-7697",
          "eventType": "running",
          "name": "Les foulées de la perle de la chalosse",
          "numberOfRaceVariants": 3,
          "place": "unknown",
          "registrationLink": "",
          "registrationStatus": "unknown",
        },
        {
          "beginning": 1785621600000,
          "city": "Penvénan",
          "departementNumber": 22,
          "ending": 1785621600000,
          "eventLink": "https://fr.milesrepublic.com/event/penvenan-color-8282",
          "eventType": "running",
          "name": "Penvénan color ",
          "numberOfRaceVariants": 2,
          "place": "unknown",
          "registrationLink": "",
          "registrationStatus": "open",
        },
        {
          "beginning": 1785621600000,
          "city": "Saint-André-de-Seignanx",
          "departementNumber": 40,
          "ending": 1785621600000,
          "eventLink": "https://fr.milesrepublic.com/event/la-galopade-andresienne-8480",
          "eventType": "running",
          "name": "La galopade andrésienne",
          "numberOfRaceVariants": 1,
          "place": "unknown",
          "registrationLink": "",
          "registrationStatus": "open",
        },
        {
          "beginning": 1785621600000,
          "city": "Mozac",
          "departementNumber": 63,
          "ending": 1785621600000,
          "eventLink": "https://fr.milesrepublic.com/event/uncentparmois-14486",
          "eventType": "cycling",
          "name": "Uncentparmois",
          "numberOfRaceVariants": 1,
          "place": "unknown",
          "registrationLink": "",
          "registrationStatus": "unknown",
        },
        {
          "beginning": 1785621600000,
          "city": "Mozac",
          "departementNumber": 63,
          "ending": 1785621600000,
          "eventLink": "https://fr.milesrepublic.com/event/dodecaudax-200-km-aout-14487",
          "eventType": "cycling",
          "name": "Dodecaudax 200 Km Aout",
          "numberOfRaceVariants": 1,
          "place": "unknown",
          "registrationLink": "",
          "registrationStatus": "unknown",
        },
      ]
    `);

    await browser.close();
  });
});
